// AudioBufferSourceNode 对象 
AudioBufferSourceNode = function AudioBufferSourceNode(){return framevm.toolsFunc.throwError("TypeError", "Failed to construct 'AudioBufferSourceNode': 1 argument required, but only 0 present.");};
framevm.toolsFunc.safeProto(AudioBufferSourceNode,"AudioBufferSourceNode");
Object.setPrototypeOf(AudioBufferSourceNode.prototype, AudioScheduledSourceNode.prototype);
framevm.toolsFunc.defineProperty(AudioBufferSourceNode.prototype, "buffer", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, AudioBufferSourceNode.prototype, "AudioBufferSourceNode", "buffer_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, AudioBufferSourceNode.prototype, "AudioBufferSourceNode", "buffer_set", arguments)}});
framevm.toolsFunc.defineProperty(AudioBufferSourceNode.prototype, "playbackRate", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, AudioBufferSourceNode.prototype, "AudioBufferSourceNode", "playbackRate_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(AudioBufferSourceNode.prototype, "detune", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, AudioBufferSourceNode.prototype, "AudioBufferSourceNode", "detune_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(AudioBufferSourceNode.prototype, "loop", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, AudioBufferSourceNode.prototype, "AudioBufferSourceNode", "loop_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, AudioBufferSourceNode.prototype, "AudioBufferSourceNode", "loop_set", arguments)}});
framevm.toolsFunc.defineProperty(AudioBufferSourceNode.prototype, "loopStart", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, AudioBufferSourceNode.prototype, "AudioBufferSourceNode", "loopStart_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, AudioBufferSourceNode.prototype, "AudioBufferSourceNode", "loopStart_set", arguments)}});
framevm.toolsFunc.defineProperty(AudioBufferSourceNode.prototype, "loopEnd", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, AudioBufferSourceNode.prototype, "AudioBufferSourceNode", "loopEnd_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, AudioBufferSourceNode.prototype, "AudioBufferSourceNode", "loopEnd_set", arguments)}});
framevm.toolsFunc.defineProperty(AudioBufferSourceNode.prototype, "start", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, AudioBufferSourceNode.prototype, "AudioBufferSourceNode", "start", arguments)}});
