// AuthenticatorAttestationResponse 对象 
AuthenticatorAttestationResponse = function AuthenticatorAttestationResponse(){return framevm.toolsFunc.throwError("TypeError", "Illegal constructor");};
framevm.toolsFunc.safeProto(AuthenticatorAttestationResponse,"AuthenticatorAttestationResponse");
Object.setPrototypeOf(AuthenticatorAttestationResponse.prototype, AuthenticatorResponse.prototype);
framevm.toolsFunc.defineProperty(AuthenticatorAttestationResponse.prototype, "attestationObject", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, AuthenticatorAttestationResponse.prototype, "AuthenticatorAttestationResponse", "attestationObject_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(AuthenticatorAttestationResponse.prototype, "getAuthenticatorData", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, AuthenticatorAttestationResponse.prototype, "AuthenticatorAttestationResponse", "getAuthenticatorData", arguments)}});
framevm.toolsFunc.defineProperty(AuthenticatorAttestationResponse.prototype, "getPublicKey", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, AuthenticatorAttestationResponse.prototype, "AuthenticatorAttestationResponse", "getPublicKey", arguments)}});
framevm.toolsFunc.defineProperty(AuthenticatorAttestationResponse.prototype, "getPublicKeyAlgorithm", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, AuthenticatorAttestationResponse.prototype, "AuthenticatorAttestationResponse", "getPublicKeyAlgorithm", arguments)}});
framevm.toolsFunc.defineProperty(AuthenticatorAttestationResponse.prototype, "getTransports", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, AuthenticatorAttestationResponse.prototype, "AuthenticatorAttestationResponse", "getTransports", arguments)}});
