// BackgroundFetchRegistration 对象 
BackgroundFetchRegistration = function BackgroundFetchRegistration(){return framevm.toolsFunc.throwError("TypeError", "Illegal constructor");};
framevm.toolsFunc.safeProto(BackgroundFetchRegistration,"BackgroundFetchRegistration");
Object.setPrototypeOf(BackgroundFetchRegistration.prototype, EventTarget.prototype);
framevm.toolsFunc.defineProperty(BackgroundFetchRegistration.prototype, "id", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, BackgroundFetchRegistration.prototype, "BackgroundFetchRegistration", "id_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(BackgroundFetchRegistration.prototype, "uploadTotal", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, BackgroundFetchRegistration.prototype, "BackgroundFetchRegistration", "uploadTotal_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(BackgroundFetchRegistration.prototype, "uploaded", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, BackgroundFetchRegistration.prototype, "BackgroundFetchRegistration", "uploaded_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(BackgroundFetchRegistration.prototype, "downloadTotal", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, BackgroundFetchRegistration.prototype, "BackgroundFetchRegistration", "downloadTotal_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(BackgroundFetchRegistration.prototype, "downloaded", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, BackgroundFetchRegistration.prototype, "BackgroundFetchRegistration", "downloaded_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(BackgroundFetchRegistration.prototype, "result", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, BackgroundFetchRegistration.prototype, "BackgroundFetchRegistration", "result_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(BackgroundFetchRegistration.prototype, "failureReason", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, BackgroundFetchRegistration.prototype, "BackgroundFetchRegistration", "failureReason_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(BackgroundFetchRegistration.prototype, "recordsAvailable", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, BackgroundFetchRegistration.prototype, "BackgroundFetchRegistration", "recordsAvailable_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(BackgroundFetchRegistration.prototype, "onprogress", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, BackgroundFetchRegistration.prototype, "BackgroundFetchRegistration", "onprogress_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, BackgroundFetchRegistration.prototype, "BackgroundFetchRegistration", "onprogress_set", arguments)}});
framevm.toolsFunc.defineProperty(BackgroundFetchRegistration.prototype, "abort", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, BackgroundFetchRegistration.prototype, "BackgroundFetchRegistration", "abort", arguments)}});
framevm.toolsFunc.defineProperty(BackgroundFetchRegistration.prototype, "match", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, BackgroundFetchRegistration.prototype, "BackgroundFetchRegistration", "match", arguments)}});
framevm.toolsFunc.defineProperty(BackgroundFetchRegistration.prototype, "matchAll", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, BackgroundFetchRegistration.prototype, "BackgroundFetchRegistration", "matchAll", arguments)}});
