// BiquadFilterNode 对象 
BiquadFilterNode = function BiquadFilterNode(){return framevm.toolsFunc.throwError("TypeError", "Failed to construct 'BiquadFilterNode': 1 argument required, but only 0 present.");};
framevm.toolsFunc.safeProto(BiquadFilterNode,"BiquadFilterNode");
Object.setPrototypeOf(BiquadFilterNode.prototype, AudioNode.prototype);
framevm.toolsFunc.defineProperty(BiquadFilterNode.prototype, "type", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, BiquadFilterNode.prototype, "BiquadFilterNode", "type_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, BiquadFilterNode.prototype, "BiquadFilterNode", "type_set", arguments)}});
framevm.toolsFunc.defineProperty(BiquadFilterNode.prototype, "frequency", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, BiquadFilterNode.prototype, "BiquadFilterNode", "frequency_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(BiquadFilterNode.prototype, "detune", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, BiquadFilterNode.prototype, "BiquadFilterNode", "detune_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(BiquadFilterNode.prototype, "Q", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, BiquadFilterNode.prototype, "BiquadFilterNode", "Q_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(BiquadFilterNode.prototype, "gain", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, BiquadFilterNode.prototype, "BiquadFilterNode", "gain_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(BiquadFilterNode.prototype, "getFrequencyResponse", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, BiquadFilterNode.prototype, "BiquadFilterNode", "getFrequencyResponse", arguments)}});
