// BluetoothRemoteGATTCharacteristic 对象 
BluetoothRemoteGATTCharacteristic = function BluetoothRemoteGATTCharacteristic(){return framevm.toolsFunc.throwError("TypeError", "Illegal constructor");};
framevm.toolsFunc.safeProto(BluetoothRemoteGATTCharacteristic,"BluetoothRemoteGATTCharacteristic");
Object.setPrototypeOf(BluetoothRemoteGATTCharacteristic.prototype, EventTarget.prototype);
framevm.toolsFunc.defineProperty(BluetoothRemoteGATTCharacteristic.prototype, "service", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, BluetoothRemoteGATTCharacteristic.prototype, "BluetoothRemoteGATTCharacteristic", "service_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(BluetoothRemoteGATTCharacteristic.prototype, "uuid", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, BluetoothRemoteGATTCharacteristic.prototype, "BluetoothRemoteGATTCharacteristic", "uuid_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(BluetoothRemoteGATTCharacteristic.prototype, "properties", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, BluetoothRemoteGATTCharacteristic.prototype, "BluetoothRemoteGATTCharacteristic", "properties_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(BluetoothRemoteGATTCharacteristic.prototype, "value", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, BluetoothRemoteGATTCharacteristic.prototype, "BluetoothRemoteGATTCharacteristic", "value_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(BluetoothRemoteGATTCharacteristic.prototype, "oncharacteristicvaluechanged", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, BluetoothRemoteGATTCharacteristic.prototype, "BluetoothRemoteGATTCharacteristic", "oncharacteristicvaluechanged_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, BluetoothRemoteGATTCharacteristic.prototype, "BluetoothRemoteGATTCharacteristic", "oncharacteristicvaluechanged_set", arguments)}});
framevm.toolsFunc.defineProperty(BluetoothRemoteGATTCharacteristic.prototype, "getDescriptor", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, BluetoothRemoteGATTCharacteristic.prototype, "BluetoothRemoteGATTCharacteristic", "getDescriptor", arguments)}});
framevm.toolsFunc.defineProperty(BluetoothRemoteGATTCharacteristic.prototype, "getDescriptors", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, BluetoothRemoteGATTCharacteristic.prototype, "BluetoothRemoteGATTCharacteristic", "getDescriptors", arguments)}});
framevm.toolsFunc.defineProperty(BluetoothRemoteGATTCharacteristic.prototype, "readValue", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, BluetoothRemoteGATTCharacteristic.prototype, "BluetoothRemoteGATTCharacteristic", "readValue", arguments)}});
framevm.toolsFunc.defineProperty(BluetoothRemoteGATTCharacteristic.prototype, "startNotifications", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, BluetoothRemoteGATTCharacteristic.prototype, "BluetoothRemoteGATTCharacteristic", "startNotifications", arguments)}});
framevm.toolsFunc.defineProperty(BluetoothRemoteGATTCharacteristic.prototype, "stopNotifications", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, BluetoothRemoteGATTCharacteristic.prototype, "BluetoothRemoteGATTCharacteristic", "stopNotifications", arguments)}});
framevm.toolsFunc.defineProperty(BluetoothRemoteGATTCharacteristic.prototype, "writeValue", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, BluetoothRemoteGATTCharacteristic.prototype, "BluetoothRemoteGATTCharacteristic", "writeValue", arguments)}});
framevm.toolsFunc.defineProperty(BluetoothRemoteGATTCharacteristic.prototype, "writeValueWithResponse", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, BluetoothRemoteGATTCharacteristic.prototype, "BluetoothRemoteGATTCharacteristic", "writeValueWithResponse", arguments)}});
framevm.toolsFunc.defineProperty(BluetoothRemoteGATTCharacteristic.prototype, "writeValueWithoutResponse", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, BluetoothRemoteGATTCharacteristic.prototype, "BluetoothRemoteGATTCharacteristic", "writeValueWithoutResponse", arguments)}});
