// BluetoothRemoteGATTServer 对象 
BluetoothRemoteGATTServer = function BluetoothRemoteGATTServer(){return framevm.toolsFunc.throwError("TypeError", "Illegal constructor");};
framevm.toolsFunc.safeProto(BluetoothRemoteGATTServer,"BluetoothRemoteGATTServer");
framevm.toolsFunc.defineProperty(BluetoothRemoteGATTServer.prototype, "device", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, BluetoothRemoteGATTServer.prototype, "BluetoothRemoteGATTServer", "device_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(BluetoothRemoteGATTServer.prototype, "connected", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, BluetoothRemoteGATTServer.prototype, "BluetoothRemoteGATTServer", "connected_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(BluetoothRemoteGATTServer.prototype, "connect", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, BluetoothRemoteGATTServer.prototype, "BluetoothRemoteGATTServer", "connect", arguments)}});
framevm.toolsFunc.defineProperty(BluetoothRemoteGATTServer.prototype, "disconnect", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, BluetoothRemoteGATTServer.prototype, "BluetoothRemoteGATTServer", "disconnect", arguments)}});
framevm.toolsFunc.defineProperty(BluetoothRemoteGATTServer.prototype, "getPrimaryService", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, BluetoothRemoteGATTServer.prototype, "BluetoothRemoteGATTServer", "getPrimaryService", arguments)}});
framevm.toolsFunc.defineProperty(BluetoothRemoteGATTServer.prototype, "getPrimaryServices", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, BluetoothRemoteGATTServer.prototype, "BluetoothRemoteGATTServer", "getPrimaryServices", arguments)}});
