// BluetoothCharacteristicProperties 对象 
BluetoothCharacteristicProperties = function BluetoothCharacteristicProperties(){return framevm.toolsFunc.throwError("TypeError", "Illegal constructor");};
framevm.toolsFunc.safeProto(BluetoothCharacteristicProperties,"BluetoothCharacteristicProperties");
framevm.toolsFunc.defineProperty(BluetoothCharacteristicProperties.prototype, "broadcast", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, BluetoothCharacteristicProperties.prototype, "BluetoothCharacteristicProperties", "broadcast_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(BluetoothCharacteristicProperties.prototype, "read", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, BluetoothCharacteristicProperties.prototype, "BluetoothCharacteristicProperties", "read_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(BluetoothCharacteristicProperties.prototype, "writeWithoutResponse", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, BluetoothCharacteristicProperties.prototype, "BluetoothCharacteristicProperties", "writeWithoutResponse_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(BluetoothCharacteristicProperties.prototype, "write", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, BluetoothCharacteristicProperties.prototype, "BluetoothCharacteristicProperties", "write_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(BluetoothCharacteristicProperties.prototype, "notify", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, BluetoothCharacteristicProperties.prototype, "BluetoothCharacteristicProperties", "notify_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(BluetoothCharacteristicProperties.prototype, "indicate", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, BluetoothCharacteristicProperties.prototype, "BluetoothCharacteristicProperties", "indicate_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(BluetoothCharacteristicProperties.prototype, "authenticatedSignedWrites", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, BluetoothCharacteristicProperties.prototype, "BluetoothCharacteristicProperties", "authenticatedSignedWrites_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(BluetoothCharacteristicProperties.prototype, "reliableWrite", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, BluetoothCharacteristicProperties.prototype, "BluetoothCharacteristicProperties", "reliableWrite_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(BluetoothCharacteristicProperties.prototype, "writableAuxiliaries", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, BluetoothCharacteristicProperties.prototype, "BluetoothCharacteristicProperties", "writableAuxiliaries_get", arguments)}, set:undefined});
