// DataTransfer 对象 
DataTransfer = function DataTransfer(){};
framevm.toolsFunc.safeProto(DataTransfer,"DataTransfer");
framevm.toolsFunc.defineProperty(DataTransfer.prototype, "dropEffect", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, DataTransfer.prototype, "DataTransfer", "dropEffect_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, DataTransfer.prototype, "DataTransfer", "dropEffect_set", arguments)}});
framevm.toolsFunc.defineProperty(DataTransfer.prototype, "effectAllowed", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, DataTransfer.prototype, "DataTransfer", "effectAllowed_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, DataTransfer.prototype, "DataTransfer", "effectAllowed_set", arguments)}});
framevm.toolsFunc.defineProperty(DataTransfer.prototype, "items", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, DataTransfer.prototype, "DataTransfer", "items_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(DataTransfer.prototype, "types", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, DataTransfer.prototype, "DataTransfer", "types_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(DataTransfer.prototype, "files", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, DataTransfer.prototype, "DataTransfer", "files_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(DataTransfer.prototype, "clearData", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, DataTransfer.prototype, "DataTransfer", "clearData", arguments)}});
framevm.toolsFunc.defineProperty(DataTransfer.prototype, "getData", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, DataTransfer.prototype, "DataTransfer", "getData", arguments)}});
framevm.toolsFunc.defineProperty(DataTransfer.prototype, "setData", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, DataTransfer.prototype, "DataTransfer", "setData", arguments)}});
framevm.toolsFunc.defineProperty(DataTransfer.prototype, "setDragImage", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, DataTransfer.prototype, "DataTransfer", "setDragImage", arguments)}});
