// DocumentFragment 对象 
DocumentFragment = function DocumentFragment(){};
framevm.toolsFunc.safeProto(DocumentFragment,"DocumentFragment");
Object.setPrototypeOf(DocumentFragment.prototype, Node.prototype);
framevm.toolsFunc.defineProperty(DocumentFragment.prototype, "children", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, DocumentFragment.prototype, "DocumentFragment", "children_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(DocumentFragment.prototype, "firstElementChild", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, DocumentFragment.prototype, "DocumentFragment", "firstElementChild_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(DocumentFragment.prototype, "lastElementChild", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, DocumentFragment.prototype, "DocumentFragment", "lastElementChild_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(DocumentFragment.prototype, "childElementCount", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, DocumentFragment.prototype, "DocumentFragment", "childElementCount_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(DocumentFragment.prototype, "append", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, DocumentFragment.prototype, "DocumentFragment", "append", arguments)}});
framevm.toolsFunc.defineProperty(DocumentFragment.prototype, "getElementById", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, DocumentFragment.prototype, "DocumentFragment", "getElementById", arguments)}});
framevm.toolsFunc.defineProperty(DocumentFragment.prototype, "prepend", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, DocumentFragment.prototype, "DocumentFragment", "prepend", arguments)}});
framevm.toolsFunc.defineProperty(DocumentFragment.prototype, "querySelector", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, DocumentFragment.prototype, "DocumentFragment", "querySelector", arguments)}});
framevm.toolsFunc.defineProperty(DocumentFragment.prototype, "querySelectorAll", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, DocumentFragment.prototype, "DocumentFragment", "querySelectorAll", arguments)}});
framevm.toolsFunc.defineProperty(DocumentFragment.prototype, "replaceChildren", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, DocumentFragment.prototype, "DocumentFragment", "replaceChildren", arguments)}});
