// DOMMatrix 对象 
DOMMatrix = function DOMMatrix(){};
framevm.toolsFunc.safeProto(DOMMatrix,"DOMMatrix");
Object.setPrototypeOf(DOMMatrix.prototype, DOMMatrixReadOnly.prototype);
framevm.toolsFunc.defineProperty(DOMMatrix, "fromFloat32Array", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, DOMMatrix, "DOMMatrix", "fromFloat32Array", arguments)}});
framevm.toolsFunc.defineProperty(DOMMatrix, "fromFloat64Array", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, DOMMatrix, "DOMMatrix", "fromFloat64Array", arguments)}});
framevm.toolsFunc.defineProperty(DOMMatrix, "fromMatrix", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, DOMMatrix, "DOMMatrix", "fromMatrix", arguments)}});
framevm.toolsFunc.defineProperty(DOMMatrix.prototype, "a", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, DOMMatrix.prototype, "DOMMatrix", "a_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, DOMMatrix.prototype, "DOMMatrix", "a_set", arguments)}});
framevm.toolsFunc.defineProperty(DOMMatrix.prototype, "b", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, DOMMatrix.prototype, "DOMMatrix", "b_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, DOMMatrix.prototype, "DOMMatrix", "b_set", arguments)}});
framevm.toolsFunc.defineProperty(DOMMatrix.prototype, "c", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, DOMMatrix.prototype, "DOMMatrix", "c_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, DOMMatrix.prototype, "DOMMatrix", "c_set", arguments)}});
framevm.toolsFunc.defineProperty(DOMMatrix.prototype, "d", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, DOMMatrix.prototype, "DOMMatrix", "d_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, DOMMatrix.prototype, "DOMMatrix", "d_set", arguments)}});
framevm.toolsFunc.defineProperty(DOMMatrix.prototype, "e", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, DOMMatrix.prototype, "DOMMatrix", "e_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, DOMMatrix.prototype, "DOMMatrix", "e_set", arguments)}});
framevm.toolsFunc.defineProperty(DOMMatrix.prototype, "f", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, DOMMatrix.prototype, "DOMMatrix", "f_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, DOMMatrix.prototype, "DOMMatrix", "f_set", arguments)}});
framevm.toolsFunc.defineProperty(DOMMatrix.prototype, "m11", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, DOMMatrix.prototype, "DOMMatrix", "m11_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, DOMMatrix.prototype, "DOMMatrix", "m11_set", arguments)}});
framevm.toolsFunc.defineProperty(DOMMatrix.prototype, "m12", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, DOMMatrix.prototype, "DOMMatrix", "m12_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, DOMMatrix.prototype, "DOMMatrix", "m12_set", arguments)}});
framevm.toolsFunc.defineProperty(DOMMatrix.prototype, "m13", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, DOMMatrix.prototype, "DOMMatrix", "m13_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, DOMMatrix.prototype, "DOMMatrix", "m13_set", arguments)}});
framevm.toolsFunc.defineProperty(DOMMatrix.prototype, "m14", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, DOMMatrix.prototype, "DOMMatrix", "m14_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, DOMMatrix.prototype, "DOMMatrix", "m14_set", arguments)}});
framevm.toolsFunc.defineProperty(DOMMatrix.prototype, "m21", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, DOMMatrix.prototype, "DOMMatrix", "m21_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, DOMMatrix.prototype, "DOMMatrix", "m21_set", arguments)}});
framevm.toolsFunc.defineProperty(DOMMatrix.prototype, "m22", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, DOMMatrix.prototype, "DOMMatrix", "m22_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, DOMMatrix.prototype, "DOMMatrix", "m22_set", arguments)}});
framevm.toolsFunc.defineProperty(DOMMatrix.prototype, "m23", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, DOMMatrix.prototype, "DOMMatrix", "m23_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, DOMMatrix.prototype, "DOMMatrix", "m23_set", arguments)}});
framevm.toolsFunc.defineProperty(DOMMatrix.prototype, "m24", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, DOMMatrix.prototype, "DOMMatrix", "m24_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, DOMMatrix.prototype, "DOMMatrix", "m24_set", arguments)}});
framevm.toolsFunc.defineProperty(DOMMatrix.prototype, "m31", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, DOMMatrix.prototype, "DOMMatrix", "m31_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, DOMMatrix.prototype, "DOMMatrix", "m31_set", arguments)}});
framevm.toolsFunc.defineProperty(DOMMatrix.prototype, "m32", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, DOMMatrix.prototype, "DOMMatrix", "m32_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, DOMMatrix.prototype, "DOMMatrix", "m32_set", arguments)}});
framevm.toolsFunc.defineProperty(DOMMatrix.prototype, "m33", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, DOMMatrix.prototype, "DOMMatrix", "m33_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, DOMMatrix.prototype, "DOMMatrix", "m33_set", arguments)}});
framevm.toolsFunc.defineProperty(DOMMatrix.prototype, "m34", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, DOMMatrix.prototype, "DOMMatrix", "m34_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, DOMMatrix.prototype, "DOMMatrix", "m34_set", arguments)}});
framevm.toolsFunc.defineProperty(DOMMatrix.prototype, "m41", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, DOMMatrix.prototype, "DOMMatrix", "m41_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, DOMMatrix.prototype, "DOMMatrix", "m41_set", arguments)}});
framevm.toolsFunc.defineProperty(DOMMatrix.prototype, "m42", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, DOMMatrix.prototype, "DOMMatrix", "m42_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, DOMMatrix.prototype, "DOMMatrix", "m42_set", arguments)}});
framevm.toolsFunc.defineProperty(DOMMatrix.prototype, "m43", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, DOMMatrix.prototype, "DOMMatrix", "m43_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, DOMMatrix.prototype, "DOMMatrix", "m43_set", arguments)}});
framevm.toolsFunc.defineProperty(DOMMatrix.prototype, "m44", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, DOMMatrix.prototype, "DOMMatrix", "m44_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, DOMMatrix.prototype, "DOMMatrix", "m44_set", arguments)}});
framevm.toolsFunc.defineProperty(DOMMatrix.prototype, "invertSelf", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, DOMMatrix.prototype, "DOMMatrix", "invertSelf", arguments)}});
framevm.toolsFunc.defineProperty(DOMMatrix.prototype, "multiplySelf", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, DOMMatrix.prototype, "DOMMatrix", "multiplySelf", arguments)}});
framevm.toolsFunc.defineProperty(DOMMatrix.prototype, "preMultiplySelf", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, DOMMatrix.prototype, "DOMMatrix", "preMultiplySelf", arguments)}});
framevm.toolsFunc.defineProperty(DOMMatrix.prototype, "rotateAxisAngleSelf", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, DOMMatrix.prototype, "DOMMatrix", "rotateAxisAngleSelf", arguments)}});
framevm.toolsFunc.defineProperty(DOMMatrix.prototype, "rotateFromVectorSelf", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, DOMMatrix.prototype, "DOMMatrix", "rotateFromVectorSelf", arguments)}});
framevm.toolsFunc.defineProperty(DOMMatrix.prototype, "rotateSelf", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, DOMMatrix.prototype, "DOMMatrix", "rotateSelf", arguments)}});
framevm.toolsFunc.defineProperty(DOMMatrix.prototype, "scale3dSelf", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, DOMMatrix.prototype, "DOMMatrix", "scale3dSelf", arguments)}});
framevm.toolsFunc.defineProperty(DOMMatrix.prototype, "scaleSelf", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, DOMMatrix.prototype, "DOMMatrix", "scaleSelf", arguments)}});
framevm.toolsFunc.defineProperty(DOMMatrix.prototype, "skewXSelf", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, DOMMatrix.prototype, "DOMMatrix", "skewXSelf", arguments)}});
framevm.toolsFunc.defineProperty(DOMMatrix.prototype, "skewYSelf", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, DOMMatrix.prototype, "DOMMatrix", "skewYSelf", arguments)}});
framevm.toolsFunc.defineProperty(DOMMatrix.prototype, "translateSelf", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, DOMMatrix.prototype, "DOMMatrix", "translateSelf", arguments)}});
framevm.toolsFunc.defineProperty(DOMMatrix.prototype, "setMatrixValue", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, DOMMatrix.prototype, "DOMMatrix", "setMatrixValue", arguments)}});
