// ElementInternals 对象 
ElementInternals = function ElementInternals(){return framevm.toolsFunc.throwError("TypeError", "Illegal constructor");};
framevm.toolsFunc.safeProto(ElementInternals,"ElementInternals");
framevm.toolsFunc.defineProperty(ElementInternals.prototype, "form", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "form_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(ElementInternals.prototype, "willValidate", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "willValidate_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(ElementInternals.prototype, "validity", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "validity_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(ElementInternals.prototype, "validationMessage", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "validationMessage_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(ElementInternals.prototype, "labels", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "labels_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(ElementInternals.prototype, "states", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "states_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(ElementInternals.prototype, "shadowRoot", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "shadowRoot_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(ElementInternals.prototype, "role", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "role_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "role_set", arguments)}});
framevm.toolsFunc.defineProperty(ElementInternals.prototype, "ariaAtomic", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "ariaAtomic_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "ariaAtomic_set", arguments)}});
framevm.toolsFunc.defineProperty(ElementInternals.prototype, "ariaAutoComplete", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "ariaAutoComplete_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "ariaAutoComplete_set", arguments)}});
framevm.toolsFunc.defineProperty(ElementInternals.prototype, "ariaBusy", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "ariaBusy_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "ariaBusy_set", arguments)}});
framevm.toolsFunc.defineProperty(ElementInternals.prototype, "ariaBrailleLabel", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "ariaBrailleLabel_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "ariaBrailleLabel_set", arguments)}});
framevm.toolsFunc.defineProperty(ElementInternals.prototype, "ariaBrailleRoleDescription", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "ariaBrailleRoleDescription_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "ariaBrailleRoleDescription_set", arguments)}});
framevm.toolsFunc.defineProperty(ElementInternals.prototype, "ariaChecked", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "ariaChecked_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "ariaChecked_set", arguments)}});
framevm.toolsFunc.defineProperty(ElementInternals.prototype, "ariaColCount", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "ariaColCount_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "ariaColCount_set", arguments)}});
framevm.toolsFunc.defineProperty(ElementInternals.prototype, "ariaColIndex", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "ariaColIndex_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "ariaColIndex_set", arguments)}});
framevm.toolsFunc.defineProperty(ElementInternals.prototype, "ariaColSpan", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "ariaColSpan_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "ariaColSpan_set", arguments)}});
framevm.toolsFunc.defineProperty(ElementInternals.prototype, "ariaCurrent", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "ariaCurrent_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "ariaCurrent_set", arguments)}});
framevm.toolsFunc.defineProperty(ElementInternals.prototype, "ariaDescription", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "ariaDescription_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "ariaDescription_set", arguments)}});
framevm.toolsFunc.defineProperty(ElementInternals.prototype, "ariaDisabled", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "ariaDisabled_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "ariaDisabled_set", arguments)}});
framevm.toolsFunc.defineProperty(ElementInternals.prototype, "ariaExpanded", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "ariaExpanded_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "ariaExpanded_set", arguments)}});
framevm.toolsFunc.defineProperty(ElementInternals.prototype, "ariaHasPopup", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "ariaHasPopup_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "ariaHasPopup_set", arguments)}});
framevm.toolsFunc.defineProperty(ElementInternals.prototype, "ariaHidden", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "ariaHidden_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "ariaHidden_set", arguments)}});
framevm.toolsFunc.defineProperty(ElementInternals.prototype, "ariaInvalid", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "ariaInvalid_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "ariaInvalid_set", arguments)}});
framevm.toolsFunc.defineProperty(ElementInternals.prototype, "ariaKeyShortcuts", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "ariaKeyShortcuts_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "ariaKeyShortcuts_set", arguments)}});
framevm.toolsFunc.defineProperty(ElementInternals.prototype, "ariaLabel", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "ariaLabel_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "ariaLabel_set", arguments)}});
framevm.toolsFunc.defineProperty(ElementInternals.prototype, "ariaLevel", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "ariaLevel_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "ariaLevel_set", arguments)}});
framevm.toolsFunc.defineProperty(ElementInternals.prototype, "ariaLive", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "ariaLive_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "ariaLive_set", arguments)}});
framevm.toolsFunc.defineProperty(ElementInternals.prototype, "ariaModal", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "ariaModal_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "ariaModal_set", arguments)}});
framevm.toolsFunc.defineProperty(ElementInternals.prototype, "ariaMultiLine", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "ariaMultiLine_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "ariaMultiLine_set", arguments)}});
framevm.toolsFunc.defineProperty(ElementInternals.prototype, "ariaMultiSelectable", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "ariaMultiSelectable_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "ariaMultiSelectable_set", arguments)}});
framevm.toolsFunc.defineProperty(ElementInternals.prototype, "ariaOrientation", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "ariaOrientation_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "ariaOrientation_set", arguments)}});
framevm.toolsFunc.defineProperty(ElementInternals.prototype, "ariaPlaceholder", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "ariaPlaceholder_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "ariaPlaceholder_set", arguments)}});
framevm.toolsFunc.defineProperty(ElementInternals.prototype, "ariaPosInSet", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "ariaPosInSet_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "ariaPosInSet_set", arguments)}});
framevm.toolsFunc.defineProperty(ElementInternals.prototype, "ariaPressed", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "ariaPressed_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "ariaPressed_set", arguments)}});
framevm.toolsFunc.defineProperty(ElementInternals.prototype, "ariaReadOnly", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "ariaReadOnly_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "ariaReadOnly_set", arguments)}});
framevm.toolsFunc.defineProperty(ElementInternals.prototype, "ariaRelevant", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "ariaRelevant_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "ariaRelevant_set", arguments)}});
framevm.toolsFunc.defineProperty(ElementInternals.prototype, "ariaRequired", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "ariaRequired_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "ariaRequired_set", arguments)}});
framevm.toolsFunc.defineProperty(ElementInternals.prototype, "ariaRoleDescription", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "ariaRoleDescription_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "ariaRoleDescription_set", arguments)}});
framevm.toolsFunc.defineProperty(ElementInternals.prototype, "ariaRowCount", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "ariaRowCount_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "ariaRowCount_set", arguments)}});
framevm.toolsFunc.defineProperty(ElementInternals.prototype, "ariaRowIndex", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "ariaRowIndex_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "ariaRowIndex_set", arguments)}});
framevm.toolsFunc.defineProperty(ElementInternals.prototype, "ariaRowSpan", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "ariaRowSpan_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "ariaRowSpan_set", arguments)}});
framevm.toolsFunc.defineProperty(ElementInternals.prototype, "ariaSelected", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "ariaSelected_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "ariaSelected_set", arguments)}});
framevm.toolsFunc.defineProperty(ElementInternals.prototype, "ariaSetSize", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "ariaSetSize_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "ariaSetSize_set", arguments)}});
framevm.toolsFunc.defineProperty(ElementInternals.prototype, "ariaSort", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "ariaSort_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "ariaSort_set", arguments)}});
framevm.toolsFunc.defineProperty(ElementInternals.prototype, "ariaValueMax", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "ariaValueMax_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "ariaValueMax_set", arguments)}});
framevm.toolsFunc.defineProperty(ElementInternals.prototype, "ariaValueMin", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "ariaValueMin_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "ariaValueMin_set", arguments)}});
framevm.toolsFunc.defineProperty(ElementInternals.prototype, "ariaValueNow", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "ariaValueNow_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "ariaValueNow_set", arguments)}});
framevm.toolsFunc.defineProperty(ElementInternals.prototype, "ariaValueText", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "ariaValueText_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "ariaValueText_set", arguments)}});
framevm.toolsFunc.defineProperty(ElementInternals.prototype, "checkValidity", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "checkValidity", arguments)}});
framevm.toolsFunc.defineProperty(ElementInternals.prototype, "reportValidity", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "reportValidity", arguments)}});
framevm.toolsFunc.defineProperty(ElementInternals.prototype, "setFormValue", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "setFormValue", arguments)}});
framevm.toolsFunc.defineProperty(ElementInternals.prototype, "setValidity", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "setValidity", arguments)}});
