// FileReader 对象 
FileReader = function FileReader(){};
framevm.toolsFunc.safeProto(FileReader,"FileReader");
Object.setPrototypeOf(FileReader.prototype, EventTarget.prototype);
framevm.toolsFunc.defineProperty(FileReader, "EMPTY", {configurable:false, enumerable:true, writable:false, value:0});
framevm.toolsFunc.defineProperty(FileReader, "LOADING", {configurable:false, enumerable:true, writable:false, value:1});
framevm.toolsFunc.defineProperty(FileReader, "DONE", {configurable:false, enumerable:true, writable:false, value:2});
framevm.toolsFunc.defineProperty(FileReader.prototype, "readyState", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, FileReader.prototype, "FileReader", "readyState_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(FileReader.prototype, "result", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, FileReader.prototype, "FileReader", "result_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(FileReader.prototype, "error", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, FileReader.prototype, "FileReader", "error_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(FileReader.prototype, "onloadstart", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, FileReader.prototype, "FileReader", "onloadstart_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, FileReader.prototype, "FileReader", "onloadstart_set", arguments)}});
framevm.toolsFunc.defineProperty(FileReader.prototype, "onprogress", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, FileReader.prototype, "FileReader", "onprogress_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, FileReader.prototype, "FileReader", "onprogress_set", arguments)}});
framevm.toolsFunc.defineProperty(FileReader.prototype, "onload", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, FileReader.prototype, "FileReader", "onload_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, FileReader.prototype, "FileReader", "onload_set", arguments)}});
framevm.toolsFunc.defineProperty(FileReader.prototype, "onabort", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, FileReader.prototype, "FileReader", "onabort_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, FileReader.prototype, "FileReader", "onabort_set", arguments)}});
framevm.toolsFunc.defineProperty(FileReader.prototype, "onerror", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, FileReader.prototype, "FileReader", "onerror_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, FileReader.prototype, "FileReader", "onerror_set", arguments)}});
framevm.toolsFunc.defineProperty(FileReader.prototype, "onloadend", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, FileReader.prototype, "FileReader", "onloadend_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, FileReader.prototype, "FileReader", "onloadend_set", arguments)}});
framevm.toolsFunc.defineProperty(FileReader.prototype, "EMPTY", {configurable:false, enumerable:true, writable:false, value:0});
framevm.toolsFunc.defineProperty(FileReader.prototype, "LOADING", {configurable:false, enumerable:true, writable:false, value:1});
framevm.toolsFunc.defineProperty(FileReader.prototype, "DONE", {configurable:false, enumerable:true, writable:false, value:2});
framevm.toolsFunc.defineProperty(FileReader.prototype, "abort", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, FileReader.prototype, "FileReader", "abort", arguments)}});
framevm.toolsFunc.defineProperty(FileReader.prototype, "readAsArrayBuffer", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, FileReader.prototype, "FileReader", "readAsArrayBuffer", arguments)}});
framevm.toolsFunc.defineProperty(FileReader.prototype, "readAsBinaryString", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, FileReader.prototype, "FileReader", "readAsBinaryString", arguments)}});
framevm.toolsFunc.defineProperty(FileReader.prototype, "readAsDataURL", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, FileReader.prototype, "FileReader", "readAsDataURL", arguments)}});
framevm.toolsFunc.defineProperty(FileReader.prototype, "readAsText", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, FileReader.prototype, "FileReader", "readAsText", arguments)}});
