// GeolocationCoordinates 对象 
GeolocationCoordinates = function GeolocationCoordinates(){return framevm.toolsFunc.throwError("TypeError", "Illegal constructor");};
framevm.toolsFunc.safeProto(GeolocationCoordinates,"GeolocationCoordinates");
framevm.toolsFunc.defineProperty(GeolocationCoordinates.prototype, "latitude", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, GeolocationCoordinates.prototype, "GeolocationCoordinates", "latitude_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(GeolocationCoordinates.prototype, "longitude", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, GeolocationCoordinates.prototype, "GeolocationCoordinates", "longitude_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(GeolocationCoordinates.prototype, "altitude", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, GeolocationCoordinates.prototype, "GeolocationCoordinates", "altitude_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(GeolocationCoordinates.prototype, "accuracy", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, GeolocationCoordinates.prototype, "GeolocationCoordinates", "accuracy_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(GeolocationCoordinates.prototype, "altitudeAccuracy", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, GeolocationCoordinates.prototype, "GeolocationCoordinates", "altitudeAccuracy_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(GeolocationCoordinates.prototype, "heading", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, GeolocationCoordinates.prototype, "GeolocationCoordinates", "heading_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(GeolocationCoordinates.prototype, "speed", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, GeolocationCoordinates.prototype, "GeolocationCoordinates", "speed_get", arguments)}, set:undefined});
