// HighlightRegistry 对象 
HighlightRegistry = function HighlightRegistry(){return framevm.toolsFunc.throwError("TypeError", "Illegal constructor");};
framevm.toolsFunc.safeProto(HighlightRegistry,"HighlightRegistry");
framevm.toolsFunc.defineProperty(HighlightRegistry.prototype, "size", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, HighlightRegistry.prototype, "HighlightRegistry", "size_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(HighlightRegistry.prototype, "clear", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, HighlightRegistry.prototype, "HighlightRegistry", "clear", arguments)}});
framevm.toolsFunc.defineProperty(HighlightRegistry.prototype, "delete", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, HighlightRegistry.prototype, "HighlightRegistry", "delete", arguments)}});
framevm.toolsFunc.defineProperty(HighlightRegistry.prototype, "entries", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, HighlightRegistry.prototype, "HighlightRegistry", "entries", arguments)}});
framevm.toolsFunc.defineProperty(HighlightRegistry.prototype, "forEach", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, HighlightRegistry.prototype, "HighlightRegistry", "forEach", arguments)}});
framevm.toolsFunc.defineProperty(HighlightRegistry.prototype, "get", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, HighlightRegistry.prototype, "HighlightRegistry", "get", arguments)}});
framevm.toolsFunc.defineProperty(HighlightRegistry.prototype, "has", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, HighlightRegistry.prototype, "HighlightRegistry", "has", arguments)}});
framevm.toolsFunc.defineProperty(HighlightRegistry.prototype, "keys", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, HighlightRegistry.prototype, "HighlightRegistry", "keys", arguments)}});
framevm.toolsFunc.defineProperty(HighlightRegistry.prototype, "set", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, HighlightRegistry.prototype, "HighlightRegistry", "set", arguments)}});
framevm.toolsFunc.defineProperty(HighlightRegistry.prototype, "values", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, HighlightRegistry.prototype, "HighlightRegistry", "values", arguments)}});
