// HTMLObjectElement 对象 
HTMLObjectElement = function HTMLObjectElement(){return framevm.toolsFunc.throwError("TypeError", "Illegal constructor");};
framevm.toolsFunc.safeProto(HTMLObjectElement,"HTMLObjectElement");
Object.setPrototypeOf(HTMLObjectElement.prototype, HTMLElement.prototype);
framevm.toolsFunc.defineProperty(HTMLObjectElement.prototype, "data", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "data_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "data_set", arguments)}});
framevm.toolsFunc.defineProperty(HTMLObjectElement.prototype, "type", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "type_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "type_set", arguments)}});
framevm.toolsFunc.defineProperty(HTMLObjectElement.prototype, "name", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "name_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "name_set", arguments)}});
framevm.toolsFunc.defineProperty(HTMLObjectElement.prototype, "useMap", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "useMap_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "useMap_set", arguments)}});
framevm.toolsFunc.defineProperty(HTMLObjectElement.prototype, "form", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "form_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(HTMLObjectElement.prototype, "width", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "width_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "width_set", arguments)}});
framevm.toolsFunc.defineProperty(HTMLObjectElement.prototype, "height", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "height_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "height_set", arguments)}});
framevm.toolsFunc.defineProperty(HTMLObjectElement.prototype, "contentDocument", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "contentDocument_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(HTMLObjectElement.prototype, "contentWindow", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "contentWindow_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(HTMLObjectElement.prototype, "willValidate", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "willValidate_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(HTMLObjectElement.prototype, "validity", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "validity_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(HTMLObjectElement.prototype, "validationMessage", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "validationMessage_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(HTMLObjectElement.prototype, "align", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "align_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "align_set", arguments)}});
framevm.toolsFunc.defineProperty(HTMLObjectElement.prototype, "archive", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "archive_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "archive_set", arguments)}});
framevm.toolsFunc.defineProperty(HTMLObjectElement.prototype, "code", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "code_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "code_set", arguments)}});
framevm.toolsFunc.defineProperty(HTMLObjectElement.prototype, "declare", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "declare_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "declare_set", arguments)}});
framevm.toolsFunc.defineProperty(HTMLObjectElement.prototype, "hspace", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "hspace_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "hspace_set", arguments)}});
framevm.toolsFunc.defineProperty(HTMLObjectElement.prototype, "standby", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "standby_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "standby_set", arguments)}});
framevm.toolsFunc.defineProperty(HTMLObjectElement.prototype, "vspace", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "vspace_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "vspace_set", arguments)}});
framevm.toolsFunc.defineProperty(HTMLObjectElement.prototype, "codeBase", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "codeBase_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "codeBase_set", arguments)}});
framevm.toolsFunc.defineProperty(HTMLObjectElement.prototype, "codeType", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "codeType_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "codeType_set", arguments)}});
framevm.toolsFunc.defineProperty(HTMLObjectElement.prototype, "border", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "border_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "border_set", arguments)}});
framevm.toolsFunc.defineProperty(HTMLObjectElement.prototype, "checkValidity", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "checkValidity", arguments)}});
framevm.toolsFunc.defineProperty(HTMLObjectElement.prototype, "getSVGDocument", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "getSVGDocument", arguments)}});
framevm.toolsFunc.defineProperty(HTMLObjectElement.prototype, "reportValidity", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "reportValidity", arguments)}});
framevm.toolsFunc.defineProperty(HTMLObjectElement.prototype, "setCustomValidity", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "setCustomValidity", arguments)}});
