// HTMLOptionElement 对象
HTMLOptionElement = function HTMLOptionElement(){return framevm.toolsFunc.throwError("TypeError", "Illegal constructor");};
framevm.toolsFunc.safeProto(HTMLOptionElement,"HTMLOptionElement");
Object.setPrototypeOf(HTMLOptionElement.prototype, HTMLElement.prototype);
framevm.toolsFunc.defineProperty(HTMLOptionElement.prototype, "disabled", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, HTMLOptionElement.prototype, "HTMLOptionElement", "disabled_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, HTMLOptionElement.prototype, "HTMLOptionElement", "disabled_set", arguments)}});
framevm.toolsFunc.defineProperty(HTMLOptionElement.prototype, "form", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, HTMLOptionElement.prototype, "HTMLOptionElement", "form_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(HTMLOptionElement.prototype, "label", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, HTMLOptionElement.prototype, "HTMLOptionElement", "label_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, HTMLOptionElement.prototype, "HTMLOptionElement", "label_set", arguments)}});
framevm.toolsFunc.defineProperty(HTMLOptionElement.prototype, "defaultSelected", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, HTMLOptionElement.prototype, "HTMLOptionElement", "defaultSelected_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, HTMLOptionElement.prototype, "HTMLOptionElement", "defaultSelected_set", arguments)}});
framevm.toolsFunc.defineProperty(HTMLOptionElement.prototype, "selected", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, HTMLOptionElement.prototype, "HTMLOptionElement", "selected_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, HTMLOptionElement.prototype, "HTMLOptionElement", "selected_set", arguments)}});
framevm.toolsFunc.defineProperty(HTMLOptionElement.prototype, "value", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, HTMLOptionElement.prototype, "HTMLOptionElement", "value_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, HTMLOptionElement.prototype, "HTMLOptionElement", "value_set", arguments)}});
framevm.toolsFunc.defineProperty(HTMLOptionElement.prototype, "text", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, HTMLOptionElement.prototype, "HTMLOptionElement", "text_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, HTMLOptionElement.prototype, "HTMLOptionElement", "text_set", arguments)}});
framevm.toolsFunc.defineProperty(HTMLOptionElement.prototype, "index", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, HTMLOptionElement.prototype, "HTMLOptionElement", "index_get", arguments)}, set:undefined});
