// HTMLMarqueeElement 对象
HTMLMarqueeElement = function HTMLMarqueeElement(){return framevm.toolsFunc.throwError("TypeError", "Illegal constructor");};
framevm.toolsFunc.safeProto(HTMLMarqueeElement,"HTMLMarqueeElement");
Object.setPrototypeOf(HTMLMarqueeElement.prototype, HTMLElement.prototype);
framevm.toolsFunc.defineProperty(HTMLMarqueeElement.prototype, "behavior", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, HTMLMarqueeElement.prototype, "HTMLMarqueeElement", "behavior_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, HTMLMarqueeElement.prototype, "HTMLMarqueeElement", "behavior_set", arguments)}});
framevm.toolsFunc.defineProperty(HTMLMarqueeElement.prototype, "bgColor", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, HTMLMarqueeElement.prototype, "HTMLMarqueeElement", "bgColor_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, HTMLMarqueeElement.prototype, "HTMLMarqueeElement", "bgColor_set", arguments)}});
framevm.toolsFunc.defineProperty(HTMLMarqueeElement.prototype, "direction", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, HTMLMarqueeElement.prototype, "HTMLMarqueeElement", "direction_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, HTMLMarqueeElement.prototype, "HTMLMarqueeElement", "direction_set", arguments)}});
framevm.toolsFunc.defineProperty(HTMLMarqueeElement.prototype, "height", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, HTMLMarqueeElement.prototype, "HTMLMarqueeElement", "height_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, HTMLMarqueeElement.prototype, "HTMLMarqueeElement", "height_set", arguments)}});
framevm.toolsFunc.defineProperty(HTMLMarqueeElement.prototype, "hspace", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, HTMLMarqueeElement.prototype, "HTMLMarqueeElement", "hspace_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, HTMLMarqueeElement.prototype, "HTMLMarqueeElement", "hspace_set", arguments)}});
framevm.toolsFunc.defineProperty(HTMLMarqueeElement.prototype, "loop", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, HTMLMarqueeElement.prototype, "HTMLMarqueeElement", "loop_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, HTMLMarqueeElement.prototype, "HTMLMarqueeElement", "loop_set", arguments)}});
framevm.toolsFunc.defineProperty(HTMLMarqueeElement.prototype, "scrollAmount", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, HTMLMarqueeElement.prototype, "HTMLMarqueeElement", "scrollAmount_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, HTMLMarqueeElement.prototype, "HTMLMarqueeElement", "scrollAmount_set", arguments)}});
framevm.toolsFunc.defineProperty(HTMLMarqueeElement.prototype, "scrollDelay", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, HTMLMarqueeElement.prototype, "HTMLMarqueeElement", "scrollDelay_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, HTMLMarqueeElement.prototype, "HTMLMarqueeElement", "scrollDelay_set", arguments)}});
framevm.toolsFunc.defineProperty(HTMLMarqueeElement.prototype, "trueSpeed", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, HTMLMarqueeElement.prototype, "HTMLMarqueeElement", "trueSpeed_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, HTMLMarqueeElement.prototype, "HTMLMarqueeElement", "trueSpeed_set", arguments)}});
framevm.toolsFunc.defineProperty(HTMLMarqueeElement.prototype, "vspace", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, HTMLMarqueeElement.prototype, "HTMLMarqueeElement", "vspace_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, HTMLMarqueeElement.prototype, "HTMLMarqueeElement", "vspace_set", arguments)}});
framevm.toolsFunc.defineProperty(HTMLMarqueeElement.prototype, "width", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, HTMLMarqueeElement.prototype, "HTMLMarqueeElement", "width_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, HTMLMarqueeElement.prototype, "HTMLMarqueeElement", "width_set", arguments)}});
framevm.toolsFunc.defineProperty(HTMLMarqueeElement.prototype, "start", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, HTMLMarqueeElement.prototype, "HTMLMarqueeElement", "start", arguments)}});
framevm.toolsFunc.defineProperty(HTMLMarqueeElement.prototype, "stop", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, HTMLMarqueeElement.prototype, "HTMLMarqueeElement", "stop", arguments)}});
