// HTMLTableSectionElement 对象 
HTMLTableSectionElement = function HTMLTableSectionElement(){return framevm.toolsFunc.throwError("TypeError", "Illegal constructor");};
framevm.toolsFunc.safeProto(HTMLTableSectionElement,"HTMLTableSectionElement");
Object.setPrototypeOf(HTMLTableSectionElement.prototype, HTMLElement.prototype);
framevm.toolsFunc.defineProperty(HTMLTableSectionElement.prototype, "rows", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, HTMLTableSectionElement.prototype, "HTMLTableSectionElement", "rows_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(HTMLTableSectionElement.prototype, "align", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, HTMLTableSectionElement.prototype, "HTMLTableSectionElement", "align_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, HTMLTableSectionElement.prototype, "HTMLTableSectionElement", "align_set", arguments)}});
framevm.toolsFunc.defineProperty(HTMLTableSectionElement.prototype, "ch", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, HTMLTableSectionElement.prototype, "HTMLTableSectionElement", "ch_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, HTMLTableSectionElement.prototype, "HTMLTableSectionElement", "ch_set", arguments)}});
framevm.toolsFunc.defineProperty(HTMLTableSectionElement.prototype, "chOff", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, HTMLTableSectionElement.prototype, "HTMLTableSectionElement", "chOff_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, HTMLTableSectionElement.prototype, "HTMLTableSectionElement", "chOff_set", arguments)}});
framevm.toolsFunc.defineProperty(HTMLTableSectionElement.prototype, "vAlign", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, HTMLTableSectionElement.prototype, "HTMLTableSectionElement", "vAlign_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, HTMLTableSectionElement.prototype, "HTMLTableSectionElement", "vAlign_set", arguments)}});
framevm.toolsFunc.defineProperty(HTMLTableSectionElement.prototype, "deleteRow", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, HTMLTableSectionElement.prototype, "HTMLTableSectionElement", "deleteRow", arguments)}});
framevm.toolsFunc.defineProperty(HTMLTableSectionElement.prototype, "insertRow", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, HTMLTableSectionElement.prototype, "HTMLTableSectionElement", "insertRow", arguments)}});
