// HTMLSourceElement 对象 
HTMLSourceElement = function HTMLSourceElement(){return framevm.toolsFunc.throwError("TypeError", "Illegal constructor");};
framevm.toolsFunc.safeProto(HTMLSourceElement,"HTMLSourceElement");
Object.setPrototypeOf(HTMLSourceElement.prototype, HTMLElement.prototype);
framevm.toolsFunc.defineProperty(HTMLSourceElement.prototype, "src", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, HTMLSourceElement.prototype, "HTMLSourceElement", "src_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, HTMLSourceElement.prototype, "HTMLSourceElement", "src_set", arguments)}});
framevm.toolsFunc.defineProperty(HTMLSourceElement.prototype, "type", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, HTMLSourceElement.prototype, "HTMLSourceElement", "type_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, HTMLSourceElement.prototype, "HTMLSourceElement", "type_set", arguments)}});
framevm.toolsFunc.defineProperty(HTMLSourceElement.prototype, "srcset", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, HTMLSourceElement.prototype, "HTMLSourceElement", "srcset_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, HTMLSourceElement.prototype, "HTMLSourceElement", "srcset_set", arguments)}});
framevm.toolsFunc.defineProperty(HTMLSourceElement.prototype, "sizes", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, HTMLSourceElement.prototype, "HTMLSourceElement", "sizes_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, HTMLSourceElement.prototype, "HTMLSourceElement", "sizes_set", arguments)}});
framevm.toolsFunc.defineProperty(HTMLSourceElement.prototype, "media", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, HTMLSourceElement.prototype, "HTMLSourceElement", "media_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, HTMLSourceElement.prototype, "HTMLSourceElement", "media_set", arguments)}});
framevm.toolsFunc.defineProperty(HTMLSourceElement.prototype, "width", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, HTMLSourceElement.prototype, "HTMLSourceElement", "width_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, HTMLSourceElement.prototype, "HTMLSourceElement", "width_set", arguments)}});
framevm.toolsFunc.defineProperty(HTMLSourceElement.prototype, "height", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, HTMLSourceElement.prototype, "HTMLSourceElement", "height_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, HTMLSourceElement.prototype, "HTMLSourceElement", "height_set", arguments)}});
