// HTMLTableColElement 对象 
HTMLTableColElement = function HTMLTableColElement(){return framevm.toolsFunc.throwError("TypeError", "Illegal constructor");};
framevm.toolsFunc.safeProto(HTMLTableColElement,"HTMLTableColElement");
Object.setPrototypeOf(HTMLTableColElement.prototype, HTMLElement.prototype);
framevm.toolsFunc.defineProperty(HTMLTableColElement.prototype, "span", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, HTMLTableColElement.prototype, "HTMLTableColElement", "span_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, HTMLTableColElement.prototype, "HTMLTableColElement", "span_set", arguments)}});
framevm.toolsFunc.defineProperty(HTMLTableColElement.prototype, "align", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, HTMLTableColElement.prototype, "HTMLTableColElement", "align_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, HTMLTableColElement.prototype, "HTMLTableColElement", "align_set", arguments)}});
framevm.toolsFunc.defineProperty(HTMLTableColElement.prototype, "ch", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, HTMLTableColElement.prototype, "HTMLTableColElement", "ch_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, HTMLTableColElement.prototype, "HTMLTableColElement", "ch_set", arguments)}});
framevm.toolsFunc.defineProperty(HTMLTableColElement.prototype, "chOff", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, HTMLTableColElement.prototype, "HTMLTableColElement", "chOff_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, HTMLTableColElement.prototype, "HTMLTableColElement", "chOff_set", arguments)}});
framevm.toolsFunc.defineProperty(HTMLTableColElement.prototype, "vAlign", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, HTMLTableColElement.prototype, "HTMLTableColElement", "vAlign_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, HTMLTableColElement.prototype, "HTMLTableColElement", "vAlign_set", arguments)}});
framevm.toolsFunc.defineProperty(HTMLTableColElement.prototype, "width", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, HTMLTableColElement.prototype, "HTMLTableColElement", "width_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, HTMLTableColElement.prototype, "HTMLTableColElement", "width_set", arguments)}});
