// HTMLFrameElement 对象 
HTMLFrameElement = function HTMLFrameElement(){return framevm.toolsFunc.throwError("TypeError", "Illegal constructor");};
framevm.toolsFunc.safeProto(HTMLFrameElement,"HTMLFrameElement");
Object.setPrototypeOf(HTMLFrameElement.prototype, HTMLElement.prototype);
framevm.toolsFunc.defineProperty(HTMLFrameElement.prototype, "name", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, HTMLFrameElement.prototype, "HTMLFrameElement", "name_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, HTMLFrameElement.prototype, "HTMLFrameElement", "name_set", arguments)}});
framevm.toolsFunc.defineProperty(HTMLFrameElement.prototype, "scrolling", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, HTMLFrameElement.prototype, "HTMLFrameElement", "scrolling_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, HTMLFrameElement.prototype, "HTMLFrameElement", "scrolling_set", arguments)}});
framevm.toolsFunc.defineProperty(HTMLFrameElement.prototype, "src", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, HTMLFrameElement.prototype, "HTMLFrameElement", "src_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, HTMLFrameElement.prototype, "HTMLFrameElement", "src_set", arguments)}});
framevm.toolsFunc.defineProperty(HTMLFrameElement.prototype, "frameBorder", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, HTMLFrameElement.prototype, "HTMLFrameElement", "frameBorder_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, HTMLFrameElement.prototype, "HTMLFrameElement", "frameBorder_set", arguments)}});
framevm.toolsFunc.defineProperty(HTMLFrameElement.prototype, "longDesc", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, HTMLFrameElement.prototype, "HTMLFrameElement", "longDesc_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, HTMLFrameElement.prototype, "HTMLFrameElement", "longDesc_set", arguments)}});
framevm.toolsFunc.defineProperty(HTMLFrameElement.prototype, "noResize", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, HTMLFrameElement.prototype, "HTMLFrameElement", "noResize_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, HTMLFrameElement.prototype, "HTMLFrameElement", "noResize_set", arguments)}});
framevm.toolsFunc.defineProperty(HTMLFrameElement.prototype, "contentDocument", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, HTMLFrameElement.prototype, "HTMLFrameElement", "contentDocument_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(HTMLFrameElement.prototype, "contentWindow", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, HTMLFrameElement.prototype, "HTMLFrameElement", "contentWindow_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(HTMLFrameElement.prototype, "marginHeight", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, HTMLFrameElement.prototype, "HTMLFrameElement", "marginHeight_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, HTMLFrameElement.prototype, "HTMLFrameElement", "marginHeight_set", arguments)}});
framevm.toolsFunc.defineProperty(HTMLFrameElement.prototype, "marginWidth", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, HTMLFrameElement.prototype, "HTMLFrameElement", "marginWidth_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, HTMLFrameElement.prototype, "HTMLFrameElement", "marginWidth_set", arguments)}});
