// HTMLHRElement 对象 
HTMLHRElement = function HTMLHRElement(){return framevm.toolsFunc.throwError("TypeError", "Illegal constructor");};
framevm.toolsFunc.safeProto(HTMLHRElement,"HTMLHRElement");
Object.setPrototypeOf(HTMLHRElement.prototype, HTMLElement.prototype);
framevm.toolsFunc.defineProperty(HTMLHRElement.prototype, "align", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, HTMLHRElement.prototype, "HTMLHRElement", "align_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, HTMLHRElement.prototype, "HTMLHRElement", "align_set", arguments)}});
framevm.toolsFunc.defineProperty(HTMLHRElement.prototype, "color", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, HTMLHRElement.prototype, "HTMLHRElement", "color_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, HTMLHRElement.prototype, "HTMLHRElement", "color_set", arguments)}});
framevm.toolsFunc.defineProperty(HTMLHRElement.prototype, "noShade", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, HTMLHRElement.prototype, "HTMLHRElement", "noShade_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, HTMLHRElement.prototype, "HTMLHRElement", "noShade_set", arguments)}});
framevm.toolsFunc.defineProperty(HTMLHRElement.prototype, "size", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, HTMLHRElement.prototype, "HTMLHRElement", "size_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, HTMLHRElement.prototype, "HTMLHRElement", "size_set", arguments)}});
framevm.toolsFunc.defineProperty(HTMLHRElement.prototype, "width", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, HTMLHRElement.prototype, "HTMLHRElement", "width_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, HTMLHRElement.prototype, "HTMLHRElement", "width_set", arguments)}});
