// IDBObjectStore 对象 
IDBObjectStore = function IDBObjectStore(){return framevm.toolsFunc.throwError("TypeError", "Illegal constructor");};
framevm.toolsFunc.safeProto(IDBObjectStore,"IDBObjectStore");
framevm.toolsFunc.defineProperty(IDBObjectStore.prototype, "name", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, IDBObjectStore.prototype, "IDBObjectStore", "name_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, IDBObjectStore.prototype, "IDBObjectStore", "name_set", arguments)}});
framevm.toolsFunc.defineProperty(IDBObjectStore.prototype, "keyPath", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, IDBObjectStore.prototype, "IDBObjectStore", "keyPath_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(IDBObjectStore.prototype, "indexNames", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, IDBObjectStore.prototype, "IDBObjectStore", "indexNames_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(IDBObjectStore.prototype, "transaction", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, IDBObjectStore.prototype, "IDBObjectStore", "transaction_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(IDBObjectStore.prototype, "autoIncrement", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, IDBObjectStore.prototype, "IDBObjectStore", "autoIncrement_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(IDBObjectStore.prototype, "add", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, IDBObjectStore.prototype, "IDBObjectStore", "add", arguments)}});
framevm.toolsFunc.defineProperty(IDBObjectStore.prototype, "clear", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, IDBObjectStore.prototype, "IDBObjectStore", "clear", arguments)}});
framevm.toolsFunc.defineProperty(IDBObjectStore.prototype, "count", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, IDBObjectStore.prototype, "IDBObjectStore", "count", arguments)}});
framevm.toolsFunc.defineProperty(IDBObjectStore.prototype, "createIndex", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, IDBObjectStore.prototype, "IDBObjectStore", "createIndex", arguments)}});
framevm.toolsFunc.defineProperty(IDBObjectStore.prototype, "delete", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, IDBObjectStore.prototype, "IDBObjectStore", "delete", arguments)}});
framevm.toolsFunc.defineProperty(IDBObjectStore.prototype, "deleteIndex", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, IDBObjectStore.prototype, "IDBObjectStore", "deleteIndex", arguments)}});
framevm.toolsFunc.defineProperty(IDBObjectStore.prototype, "get", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, IDBObjectStore.prototype, "IDBObjectStore", "get", arguments)}});
framevm.toolsFunc.defineProperty(IDBObjectStore.prototype, "getAll", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, IDBObjectStore.prototype, "IDBObjectStore", "getAll", arguments)}});
framevm.toolsFunc.defineProperty(IDBObjectStore.prototype, "getAllKeys", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, IDBObjectStore.prototype, "IDBObjectStore", "getAllKeys", arguments)}});
framevm.toolsFunc.defineProperty(IDBObjectStore.prototype, "getKey", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, IDBObjectStore.prototype, "IDBObjectStore", "getKey", arguments)}});
framevm.toolsFunc.defineProperty(IDBObjectStore.prototype, "index", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, IDBObjectStore.prototype, "IDBObjectStore", "index", arguments)}});
framevm.toolsFunc.defineProperty(IDBObjectStore.prototype, "openCursor", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, IDBObjectStore.prototype, "IDBObjectStore", "openCursor", arguments)}});
framevm.toolsFunc.defineProperty(IDBObjectStore.prototype, "openKeyCursor", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, IDBObjectStore.prototype, "IDBObjectStore", "openKeyCursor", arguments)}});
framevm.toolsFunc.defineProperty(IDBObjectStore.prototype, "put", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, IDBObjectStore.prototype, "IDBObjectStore", "put", arguments)}});
