// IDBTransaction 对象 
IDBTransaction = function IDBTransaction(){return framevm.toolsFunc.throwError("TypeError", "Illegal constructor");};
framevm.toolsFunc.safeProto(IDBTransaction,"IDBTransaction");
Object.setPrototypeOf(IDBTransaction.prototype, EventTarget.prototype);
framevm.toolsFunc.defineProperty(IDBTransaction.prototype, "objectStoreNames", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, IDBTransaction.prototype, "IDBTransaction", "objectStoreNames_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(IDBTransaction.prototype, "mode", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, IDBTransaction.prototype, "IDBTransaction", "mode_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(IDBTransaction.prototype, "durability", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, IDBTransaction.prototype, "IDBTransaction", "durability_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(IDBTransaction.prototype, "db", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, IDBTransaction.prototype, "IDBTransaction", "db_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(IDBTransaction.prototype, "error", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, IDBTransaction.prototype, "IDBTransaction", "error_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(IDBTransaction.prototype, "onabort", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, IDBTransaction.prototype, "IDBTransaction", "onabort_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, IDBTransaction.prototype, "IDBTransaction", "onabort_set", arguments)}});
framevm.toolsFunc.defineProperty(IDBTransaction.prototype, "oncomplete", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, IDBTransaction.prototype, "IDBTransaction", "oncomplete_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, IDBTransaction.prototype, "IDBTransaction", "oncomplete_set", arguments)}});
framevm.toolsFunc.defineProperty(IDBTransaction.prototype, "onerror", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, IDBTransaction.prototype, "IDBTransaction", "onerror_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, IDBTransaction.prototype, "IDBTransaction", "onerror_set", arguments)}});
framevm.toolsFunc.defineProperty(IDBTransaction.prototype, "abort", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, IDBTransaction.prototype, "IDBTransaction", "abort", arguments)}});
framevm.toolsFunc.defineProperty(IDBTransaction.prototype, "commit", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, IDBTransaction.prototype, "IDBTransaction", "commit", arguments)}});
framevm.toolsFunc.defineProperty(IDBTransaction.prototype, "objectStore", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, IDBTransaction.prototype, "IDBTransaction", "objectStore", arguments)}});
