// Image 对象 
Image = function Image(){};
framevm.toolsFunc.safeProto(Image,"Image");
Object.setPrototypeOf(Image.prototype, HTMLElement.prototype);
framevm.toolsFunc.defineProperty(Image.prototype, "alt", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, Image.prototype, "Image", "alt_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, Image.prototype, "Image", "alt_set", arguments)}});
framevm.toolsFunc.defineProperty(Image.prototype, "src", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, Image.prototype, "Image", "src_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, Image.prototype, "Image", "src_set", arguments)}});
framevm.toolsFunc.defineProperty(Image.prototype, "srcset", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, Image.prototype, "Image", "srcset_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, Image.prototype, "Image", "srcset_set", arguments)}});
framevm.toolsFunc.defineProperty(Image.prototype, "sizes", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, Image.prototype, "Image", "sizes_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, Image.prototype, "Image", "sizes_set", arguments)}});
framevm.toolsFunc.defineProperty(Image.prototype, "crossOrigin", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, Image.prototype, "Image", "crossOrigin_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, Image.prototype, "Image", "crossOrigin_set", arguments)}});
framevm.toolsFunc.defineProperty(Image.prototype, "useMap", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, Image.prototype, "Image", "useMap_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, Image.prototype, "Image", "useMap_set", arguments)}});
framevm.toolsFunc.defineProperty(Image.prototype, "isMap", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, Image.prototype, "Image", "isMap_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, Image.prototype, "Image", "isMap_set", arguments)}});
framevm.toolsFunc.defineProperty(Image.prototype, "width", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, Image.prototype, "Image", "width_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, Image.prototype, "Image", "width_set", arguments)}});
framevm.toolsFunc.defineProperty(Image.prototype, "height", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, Image.prototype, "Image", "height_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, Image.prototype, "Image", "height_set", arguments)}});
framevm.toolsFunc.defineProperty(Image.prototype, "naturalWidth", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, Image.prototype, "Image", "naturalWidth_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(Image.prototype, "naturalHeight", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, Image.prototype, "Image", "naturalHeight_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(Image.prototype, "complete", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, Image.prototype, "Image", "complete_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(Image.prototype, "currentSrc", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, Image.prototype, "Image", "currentSrc_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(Image.prototype, "referrerPolicy", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, Image.prototype, "Image", "referrerPolicy_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, Image.prototype, "Image", "referrerPolicy_set", arguments)}});
framevm.toolsFunc.defineProperty(Image.prototype, "decoding", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, Image.prototype, "Image", "decoding_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, Image.prototype, "Image", "decoding_set", arguments)}});
framevm.toolsFunc.defineProperty(Image.prototype, "name", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, Image.prototype, "Image", "name_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, Image.prototype, "Image", "name_set", arguments)}});
framevm.toolsFunc.defineProperty(Image.prototype, "lowsrc", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, Image.prototype, "Image", "lowsrc_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, Image.prototype, "Image", "lowsrc_set", arguments)}});
framevm.toolsFunc.defineProperty(Image.prototype, "align", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, Image.prototype, "Image", "align_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, Image.prototype, "Image", "align_set", arguments)}});
framevm.toolsFunc.defineProperty(Image.prototype, "hspace", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, Image.prototype, "Image", "hspace_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, Image.prototype, "Image", "hspace_set", arguments)}});
framevm.toolsFunc.defineProperty(Image.prototype, "vspace", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, Image.prototype, "Image", "vspace_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, Image.prototype, "Image", "vspace_set", arguments)}});
framevm.toolsFunc.defineProperty(Image.prototype, "longDesc", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, Image.prototype, "Image", "longDesc_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, Image.prototype, "Image", "longDesc_set", arguments)}});
framevm.toolsFunc.defineProperty(Image.prototype, "border", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, Image.prototype, "Image", "border_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, Image.prototype, "Image", "border_set", arguments)}});
framevm.toolsFunc.defineProperty(Image.prototype, "x", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, Image.prototype, "Image", "x_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(Image.prototype, "y", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, Image.prototype, "Image", "y_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(Image.prototype, "decode", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, Image.prototype, "Image", "decode", arguments)}});
framevm.toolsFunc.defineProperty(Image.prototype, "fetchPriority", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, Image.prototype, "Image", "fetchPriority_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, Image.prototype, "Image", "fetchPriority_set", arguments)}});
framevm.toolsFunc.defineProperty(Image.prototype, "loading", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, Image.prototype, "Image", "loading_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, Image.prototype, "Image", "loading_set", arguments)}});
