// IntersectionObserver 对象 
IntersectionObserver = function IntersectionObserver(){return framevm.toolsFunc.throwError("TypeError", "Failed to construct 'IntersectionObserver': 1 argument required, but only 0 present.");};
framevm.toolsFunc.safeProto(IntersectionObserver,"IntersectionObserver");
framevm.toolsFunc.defineProperty(IntersectionObserver.prototype, "root", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, IntersectionObserver.prototype, "IntersectionObserver", "root_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(IntersectionObserver.prototype, "rootMargin", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, IntersectionObserver.prototype, "IntersectionObserver", "rootMargin_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(IntersectionObserver.prototype, "thresholds", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, IntersectionObserver.prototype, "IntersectionObserver", "thresholds_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(IntersectionObserver.prototype, "delay", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, IntersectionObserver.prototype, "IntersectionObserver", "delay_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(IntersectionObserver.prototype, "trackVisibility", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, IntersectionObserver.prototype, "IntersectionObserver", "trackVisibility_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(IntersectionObserver.prototype, "disconnect", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, IntersectionObserver.prototype, "IntersectionObserver", "disconnect", arguments)}});
framevm.toolsFunc.defineProperty(IntersectionObserver.prototype, "observe", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, IntersectionObserver.prototype, "IntersectionObserver", "observe", arguments)}});
framevm.toolsFunc.defineProperty(IntersectionObserver.prototype, "takeRecords", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, IntersectionObserver.prototype, "IntersectionObserver", "takeRecords", arguments)}});
framevm.toolsFunc.defineProperty(IntersectionObserver.prototype, "unobserve", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, IntersectionObserver.prototype, "IntersectionObserver", "unobserve", arguments)}});
