// KeyframeEffect 对象 
KeyframeEffect = function KeyframeEffect(){return framevm.toolsFunc.throwError("TypeError", "Failed to construct 'KeyframeEffect': 1 argument required, but only 0 present.");};
framevm.toolsFunc.safeProto(KeyframeEffect,"KeyframeEffect");
Object.setPrototypeOf(KeyframeEffect.prototype, AnimationEffect.prototype);
framevm.toolsFunc.defineProperty(KeyframeEffect.prototype, "target", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, KeyframeEffect.prototype, "KeyframeEffect", "target_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, KeyframeEffect.prototype, "KeyframeEffect", "target_set", arguments)}});
framevm.toolsFunc.defineProperty(KeyframeEffect.prototype, "pseudoElement", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, KeyframeEffect.prototype, "KeyframeEffect", "pseudoElement_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, KeyframeEffect.prototype, "KeyframeEffect", "pseudoElement_set", arguments)}});
framevm.toolsFunc.defineProperty(KeyframeEffect.prototype, "composite", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, KeyframeEffect.prototype, "KeyframeEffect", "composite_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, KeyframeEffect.prototype, "KeyframeEffect", "composite_set", arguments)}});
framevm.toolsFunc.defineProperty(KeyframeEffect.prototype, "getKeyframes", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, KeyframeEffect.prototype, "KeyframeEffect", "getKeyframes", arguments)}});
framevm.toolsFunc.defineProperty(KeyframeEffect.prototype, "setKeyframes", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, KeyframeEffect.prototype, "KeyframeEffect", "setKeyframes", arguments)}});
