// MathMLElement 对象 
MathMLElement = function MathMLElement(){return framevm.toolsFunc.throwError("TypeError", "Illegal constructor");};
framevm.toolsFunc.safeProto(MathMLElement,"MathMLElement");
Object.setPrototypeOf(MathMLElement.prototype, Element.prototype);
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "onbeforexrselect", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onbeforexrselect_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onbeforexrselect_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "onabort", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onabort_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onabort_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "onbeforeinput", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onbeforeinput_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onbeforeinput_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "onblur", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onblur_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onblur_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "oncancel", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "oncancel_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "oncancel_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "oncanplay", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "oncanplay_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "oncanplay_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "oncanplaythrough", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "oncanplaythrough_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "oncanplaythrough_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "onchange", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onchange_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onchange_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "onclick", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onclick_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onclick_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "onclose", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onclose_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onclose_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "oncontextlost", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "oncontextlost_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "oncontextlost_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "oncontextmenu", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "oncontextmenu_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "oncontextmenu_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "oncontextrestored", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "oncontextrestored_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "oncontextrestored_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "oncuechange", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "oncuechange_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "oncuechange_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "ondblclick", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "ondblclick_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "ondblclick_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "ondrag", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "ondrag_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "ondrag_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "ondragend", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "ondragend_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "ondragend_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "ondragenter", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "ondragenter_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "ondragenter_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "ondragleave", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "ondragleave_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "ondragleave_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "ondragover", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "ondragover_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "ondragover_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "ondragstart", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "ondragstart_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "ondragstart_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "ondrop", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "ondrop_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "ondrop_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "ondurationchange", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "ondurationchange_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "ondurationchange_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "onemptied", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onemptied_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onemptied_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "onended", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onended_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onended_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "onerror", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onerror_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onerror_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "onfocus", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onfocus_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onfocus_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "onformdata", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onformdata_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onformdata_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "oninput", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "oninput_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "oninput_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "oninvalid", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "oninvalid_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "oninvalid_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "onkeydown", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onkeydown_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onkeydown_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "onkeypress", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onkeypress_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onkeypress_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "onkeyup", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onkeyup_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onkeyup_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "onload", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onload_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onload_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "onloadeddata", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onloadeddata_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onloadeddata_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "onloadedmetadata", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onloadedmetadata_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onloadedmetadata_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "onloadstart", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onloadstart_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onloadstart_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "onmousedown", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onmousedown_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onmousedown_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "onmouseenter", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onmouseenter_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onmouseenter_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "onmouseleave", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onmouseleave_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onmouseleave_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "onmousemove", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onmousemove_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onmousemove_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "onmouseout", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onmouseout_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onmouseout_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "onmouseover", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onmouseover_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onmouseover_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "onmouseup", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onmouseup_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onmouseup_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "onmousewheel", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onmousewheel_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onmousewheel_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "onpause", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onpause_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onpause_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "onplay", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onplay_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onplay_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "onplaying", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onplaying_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onplaying_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "onprogress", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onprogress_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onprogress_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "onratechange", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onratechange_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onratechange_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "onreset", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onreset_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onreset_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "onresize", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onresize_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onresize_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "onscroll", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onscroll_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onscroll_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "onsecuritypolicyviolation", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onsecuritypolicyviolation_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onsecuritypolicyviolation_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "onseeked", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onseeked_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onseeked_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "onseeking", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onseeking_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onseeking_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "onselect", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onselect_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onselect_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "onslotchange", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onslotchange_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onslotchange_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "onstalled", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onstalled_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onstalled_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "onsubmit", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onsubmit_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onsubmit_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "onsuspend", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onsuspend_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onsuspend_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "ontimeupdate", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "ontimeupdate_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "ontimeupdate_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "ontoggle", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "ontoggle_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "ontoggle_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "onvolumechange", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onvolumechange_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onvolumechange_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "onwaiting", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onwaiting_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onwaiting_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "onwebkitanimationend", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onwebkitanimationend_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onwebkitanimationend_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "onwebkitanimationiteration", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onwebkitanimationiteration_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onwebkitanimationiteration_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "onwebkitanimationstart", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onwebkitanimationstart_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onwebkitanimationstart_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "onwebkittransitionend", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onwebkittransitionend_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onwebkittransitionend_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "onwheel", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onwheel_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onwheel_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "onauxclick", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onauxclick_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onauxclick_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "ongotpointercapture", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "ongotpointercapture_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "ongotpointercapture_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "onlostpointercapture", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onlostpointercapture_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onlostpointercapture_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "onpointerdown", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onpointerdown_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onpointerdown_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "onpointermove", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onpointermove_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onpointermove_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "onpointerrawupdate", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onpointerrawupdate_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onpointerrawupdate_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "onpointerup", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onpointerup_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onpointerup_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "onpointercancel", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onpointercancel_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onpointercancel_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "onpointerover", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onpointerover_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onpointerover_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "onpointerout", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onpointerout_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onpointerout_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "onpointerenter", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onpointerenter_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onpointerenter_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "onpointerleave", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onpointerleave_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onpointerleave_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "onselectstart", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onselectstart_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onselectstart_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "onselectionchange", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onselectionchange_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onselectionchange_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "onanimationend", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onanimationend_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onanimationend_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "onanimationiteration", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onanimationiteration_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onanimationiteration_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "onanimationstart", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onanimationstart_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onanimationstart_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "ontransitionrun", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "ontransitionrun_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "ontransitionrun_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "ontransitionstart", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "ontransitionstart_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "ontransitionstart_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "ontransitionend", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "ontransitionend_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "ontransitionend_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "ontransitioncancel", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "ontransitioncancel_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "ontransitioncancel_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "oncopy", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "oncopy_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "oncopy_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "oncut", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "oncut_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "oncut_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "onpaste", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onpaste_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onpaste_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "dataset", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "dataset_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "nonce", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "nonce_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "nonce_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "autofocus", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "autofocus_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "autofocus_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "tabIndex", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "tabIndex_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "tabIndex_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "style", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "style_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "style_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "attributeStyleMap", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "attributeStyleMap_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "blur", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "blur", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "focus", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "focus", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "oncontentvisibilityautostatechange", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "oncontentvisibilityautostatechange_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "oncontentvisibilityautostatechange_set", arguments)}});
framevm.toolsFunc.defineProperty(MathMLElement.prototype, "onbeforematch", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onbeforematch_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "onbeforematch_set", arguments)}});
