// NavigationHistoryEntry 对象 
NavigationHistoryEntry = function NavigationHistoryEntry(){return framevm.toolsFunc.throwError("TypeError", "Illegal constructor");};
framevm.toolsFunc.safeProto(NavigationHistoryEntry,"NavigationHistoryEntry");
Object.setPrototypeOf(NavigationHistoryEntry.prototype, EventTarget.prototype);
framevm.toolsFunc.defineProperty(NavigationHistoryEntry.prototype, "key", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, NavigationHistoryEntry.prototype, "NavigationHistoryEntry", "key_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(NavigationHistoryEntry.prototype, "id", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, NavigationHistoryEntry.prototype, "NavigationHistoryEntry", "id_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(NavigationHistoryEntry.prototype, "url", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, NavigationHistoryEntry.prototype, "NavigationHistoryEntry", "url_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(NavigationHistoryEntry.prototype, "index", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, NavigationHistoryEntry.prototype, "NavigationHistoryEntry", "index_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(NavigationHistoryEntry.prototype, "sameDocument", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, NavigationHistoryEntry.prototype, "NavigationHistoryEntry", "sameDocument_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(NavigationHistoryEntry.prototype, "ondispose", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, NavigationHistoryEntry.prototype, "NavigationHistoryEntry", "ondispose_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, NavigationHistoryEntry.prototype, "NavigationHistoryEntry", "ondispose_set", arguments)}});
framevm.toolsFunc.defineProperty(NavigationHistoryEntry.prototype, "getState", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, NavigationHistoryEntry.prototype, "NavigationHistoryEntry", "getState", arguments)}});
