// Navigation 对象 
Navigation = function Navigation(){return framevm.toolsFunc.throwError("TypeError", "Illegal constructor");};
framevm.toolsFunc.safeProto(Navigation,"Navigation");
Object.setPrototypeOf(Navigation.prototype, EventTarget.prototype);
framevm.toolsFunc.defineProperty(Navigation.prototype, "currentEntry", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, Navigation.prototype, "Navigation", "currentEntry_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(Navigation.prototype, "transition", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, Navigation.prototype, "Navigation", "transition_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(Navigation.prototype, "canGoBack", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, Navigation.prototype, "Navigation", "canGoBack_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(Navigation.prototype, "canGoForward", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, Navigation.prototype, "Navigation", "canGoForward_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(Navigation.prototype, "onnavigate", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, Navigation.prototype, "Navigation", "onnavigate_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, Navigation.prototype, "Navigation", "onnavigate_set", arguments)}});
framevm.toolsFunc.defineProperty(Navigation.prototype, "onnavigatesuccess", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, Navigation.prototype, "Navigation", "onnavigatesuccess_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, Navigation.prototype, "Navigation", "onnavigatesuccess_set", arguments)}});
framevm.toolsFunc.defineProperty(Navigation.prototype, "onnavigateerror", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, Navigation.prototype, "Navigation", "onnavigateerror_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, Navigation.prototype, "Navigation", "onnavigateerror_set", arguments)}});
framevm.toolsFunc.defineProperty(Navigation.prototype, "oncurrententrychange", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, Navigation.prototype, "Navigation", "oncurrententrychange_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, Navigation.prototype, "Navigation", "oncurrententrychange_set", arguments)}});
framevm.toolsFunc.defineProperty(Navigation.prototype, "back", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, Navigation.prototype, "Navigation", "back", arguments)}});
framevm.toolsFunc.defineProperty(Navigation.prototype, "entries", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, Navigation.prototype, "Navigation", "entries", arguments)}});
framevm.toolsFunc.defineProperty(Navigation.prototype, "forward", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, Navigation.prototype, "Navigation", "forward", arguments)}});
framevm.toolsFunc.defineProperty(Navigation.prototype, "navigate", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, Navigation.prototype, "Navigation", "navigate", arguments)}});
framevm.toolsFunc.defineProperty(Navigation.prototype, "reload", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, Navigation.prototype, "Navigation", "reload", arguments)}});
framevm.toolsFunc.defineProperty(Navigation.prototype, "traverseTo", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, Navigation.prototype, "Navigation", "traverseTo", arguments)}});
framevm.toolsFunc.defineProperty(Navigation.prototype, "updateCurrentEntry", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, Navigation.prototype, "Navigation", "updateCurrentEntry", arguments)}});
