// OffscreenCanvas 对象 
OffscreenCanvas = function OffscreenCanvas(){return framevm.toolsFunc.throwError("TypeError", "Failed to construct 'OffscreenCanvas': 2 arguments required, but only 0 present.");};
framevm.toolsFunc.safeProto(OffscreenCanvas,"OffscreenCanvas");
Object.setPrototypeOf(OffscreenCanvas.prototype, EventTarget.prototype);
framevm.toolsFunc.defineProperty(OffscreenCanvas.prototype, "width", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvas.prototype, "OffscreenCanvas", "width_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvas.prototype, "OffscreenCanvas", "width_set", arguments)}});
framevm.toolsFunc.defineProperty(OffscreenCanvas.prototype, "height", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvas.prototype, "OffscreenCanvas", "height_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvas.prototype, "OffscreenCanvas", "height_set", arguments)}});
framevm.toolsFunc.defineProperty(OffscreenCanvas.prototype, "oncontextlost", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvas.prototype, "OffscreenCanvas", "oncontextlost_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvas.prototype, "OffscreenCanvas", "oncontextlost_set", arguments)}});
framevm.toolsFunc.defineProperty(OffscreenCanvas.prototype, "oncontextrestored", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvas.prototype, "OffscreenCanvas", "oncontextrestored_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvas.prototype, "OffscreenCanvas", "oncontextrestored_set", arguments)}});
framevm.toolsFunc.defineProperty(OffscreenCanvas.prototype, "convertToBlob", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvas.prototype, "OffscreenCanvas", "convertToBlob", arguments)}});
framevm.toolsFunc.defineProperty(OffscreenCanvas.prototype, "getContext", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvas.prototype, "OffscreenCanvas", "getContext", arguments)}});
framevm.toolsFunc.defineProperty(OffscreenCanvas.prototype, "transferToImageBitmap", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvas.prototype, "OffscreenCanvas", "transferToImageBitmap", arguments)}});
