// OffscreenCanvasRenderingContext2D 对象 
OffscreenCanvasRenderingContext2D = function OffscreenCanvasRenderingContext2D(){return framevm.toolsFunc.throwError("TypeError", "Illegal constructor");};
framevm.toolsFunc.safeProto(OffscreenCanvasRenderingContext2D,"OffscreenCanvasRenderingContext2D");
framevm.toolsFunc.defineProperty(OffscreenCanvasRenderingContext2D.prototype, "canvas", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "canvas_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(OffscreenCanvasRenderingContext2D.prototype, "globalAlpha", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "globalAlpha_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "globalAlpha_set", arguments)}});
framevm.toolsFunc.defineProperty(OffscreenCanvasRenderingContext2D.prototype, "globalCompositeOperation", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "globalCompositeOperation_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "globalCompositeOperation_set", arguments)}});
framevm.toolsFunc.defineProperty(OffscreenCanvasRenderingContext2D.prototype, "filter", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "filter_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "filter_set", arguments)}});
framevm.toolsFunc.defineProperty(OffscreenCanvasRenderingContext2D.prototype, "imageSmoothingEnabled", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "imageSmoothingEnabled_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "imageSmoothingEnabled_set", arguments)}});
framevm.toolsFunc.defineProperty(OffscreenCanvasRenderingContext2D.prototype, "imageSmoothingQuality", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "imageSmoothingQuality_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "imageSmoothingQuality_set", arguments)}});
framevm.toolsFunc.defineProperty(OffscreenCanvasRenderingContext2D.prototype, "strokeStyle", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "strokeStyle_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "strokeStyle_set", arguments)}});
framevm.toolsFunc.defineProperty(OffscreenCanvasRenderingContext2D.prototype, "fillStyle", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "fillStyle_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "fillStyle_set", arguments)}});
framevm.toolsFunc.defineProperty(OffscreenCanvasRenderingContext2D.prototype, "shadowOffsetX", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "shadowOffsetX_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "shadowOffsetX_set", arguments)}});
framevm.toolsFunc.defineProperty(OffscreenCanvasRenderingContext2D.prototype, "shadowOffsetY", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "shadowOffsetY_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "shadowOffsetY_set", arguments)}});
framevm.toolsFunc.defineProperty(OffscreenCanvasRenderingContext2D.prototype, "shadowBlur", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "shadowBlur_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "shadowBlur_set", arguments)}});
framevm.toolsFunc.defineProperty(OffscreenCanvasRenderingContext2D.prototype, "shadowColor", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "shadowColor_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "shadowColor_set", arguments)}});
framevm.toolsFunc.defineProperty(OffscreenCanvasRenderingContext2D.prototype, "lineWidth", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "lineWidth_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "lineWidth_set", arguments)}});
framevm.toolsFunc.defineProperty(OffscreenCanvasRenderingContext2D.prototype, "lineCap", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "lineCap_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "lineCap_set", arguments)}});
framevm.toolsFunc.defineProperty(OffscreenCanvasRenderingContext2D.prototype, "lineJoin", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "lineJoin_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "lineJoin_set", arguments)}});
framevm.toolsFunc.defineProperty(OffscreenCanvasRenderingContext2D.prototype, "miterLimit", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "miterLimit_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "miterLimit_set", arguments)}});
framevm.toolsFunc.defineProperty(OffscreenCanvasRenderingContext2D.prototype, "lineDashOffset", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "lineDashOffset_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "lineDashOffset_set", arguments)}});
framevm.toolsFunc.defineProperty(OffscreenCanvasRenderingContext2D.prototype, "font", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "font_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "font_set", arguments)}});
framevm.toolsFunc.defineProperty(OffscreenCanvasRenderingContext2D.prototype, "textAlign", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "textAlign_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "textAlign_set", arguments)}});
framevm.toolsFunc.defineProperty(OffscreenCanvasRenderingContext2D.prototype, "textBaseline", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "textBaseline_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "textBaseline_set", arguments)}});
framevm.toolsFunc.defineProperty(OffscreenCanvasRenderingContext2D.prototype, "direction", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "direction_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "direction_set", arguments)}});
framevm.toolsFunc.defineProperty(OffscreenCanvasRenderingContext2D.prototype, "fontKerning", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "fontKerning_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "fontKerning_set", arguments)}});
framevm.toolsFunc.defineProperty(OffscreenCanvasRenderingContext2D.prototype, "fontStretch", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "fontStretch_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "fontStretch_set", arguments)}});
framevm.toolsFunc.defineProperty(OffscreenCanvasRenderingContext2D.prototype, "fontVariantCaps", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "fontVariantCaps_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "fontVariantCaps_set", arguments)}});
framevm.toolsFunc.defineProperty(OffscreenCanvasRenderingContext2D.prototype, "letterSpacing", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "letterSpacing_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "letterSpacing_set", arguments)}});
framevm.toolsFunc.defineProperty(OffscreenCanvasRenderingContext2D.prototype, "textRendering", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "textRendering_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "textRendering_set", arguments)}});
framevm.toolsFunc.defineProperty(OffscreenCanvasRenderingContext2D.prototype, "wordSpacing", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "wordSpacing_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "wordSpacing_set", arguments)}});
framevm.toolsFunc.defineProperty(OffscreenCanvasRenderingContext2D.prototype, "clip", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "clip", arguments)}});
framevm.toolsFunc.defineProperty(OffscreenCanvasRenderingContext2D.prototype, "createConicGradient", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "createConicGradient", arguments)}});
framevm.toolsFunc.defineProperty(OffscreenCanvasRenderingContext2D.prototype, "createImageData", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "createImageData", arguments)}});
framevm.toolsFunc.defineProperty(OffscreenCanvasRenderingContext2D.prototype, "createLinearGradient", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "createLinearGradient", arguments)}});
framevm.toolsFunc.defineProperty(OffscreenCanvasRenderingContext2D.prototype, "createPattern", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "createPattern", arguments)}});
framevm.toolsFunc.defineProperty(OffscreenCanvasRenderingContext2D.prototype, "createRadialGradient", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "createRadialGradient", arguments)}});
framevm.toolsFunc.defineProperty(OffscreenCanvasRenderingContext2D.prototype, "drawImage", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "drawImage", arguments)}});
framevm.toolsFunc.defineProperty(OffscreenCanvasRenderingContext2D.prototype, "fill", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "fill", arguments)}});
framevm.toolsFunc.defineProperty(OffscreenCanvasRenderingContext2D.prototype, "fillText", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "fillText", arguments)}});
framevm.toolsFunc.defineProperty(OffscreenCanvasRenderingContext2D.prototype, "getImageData", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "getImageData", arguments)}});
framevm.toolsFunc.defineProperty(OffscreenCanvasRenderingContext2D.prototype, "getLineDash", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "getLineDash", arguments)}});
framevm.toolsFunc.defineProperty(OffscreenCanvasRenderingContext2D.prototype, "getTransform", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "getTransform", arguments)}});
framevm.toolsFunc.defineProperty(OffscreenCanvasRenderingContext2D.prototype, "isContextLost", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "isContextLost", arguments)}});
framevm.toolsFunc.defineProperty(OffscreenCanvasRenderingContext2D.prototype, "isPointInPath", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "isPointInPath", arguments)}});
framevm.toolsFunc.defineProperty(OffscreenCanvasRenderingContext2D.prototype, "isPointInStroke", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "isPointInStroke", arguments)}});
framevm.toolsFunc.defineProperty(OffscreenCanvasRenderingContext2D.prototype, "measureText", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "measureText", arguments)}});
framevm.toolsFunc.defineProperty(OffscreenCanvasRenderingContext2D.prototype, "putImageData", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "putImageData", arguments)}});
framevm.toolsFunc.defineProperty(OffscreenCanvasRenderingContext2D.prototype, "reset", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "reset", arguments)}});
framevm.toolsFunc.defineProperty(OffscreenCanvasRenderingContext2D.prototype, "roundRect", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "roundRect", arguments)}});
framevm.toolsFunc.defineProperty(OffscreenCanvasRenderingContext2D.prototype, "save", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "save", arguments)}});
framevm.toolsFunc.defineProperty(OffscreenCanvasRenderingContext2D.prototype, "scale", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "scale", arguments)}});
framevm.toolsFunc.defineProperty(OffscreenCanvasRenderingContext2D.prototype, "setLineDash", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "setLineDash", arguments)}});
framevm.toolsFunc.defineProperty(OffscreenCanvasRenderingContext2D.prototype, "setTransform", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "setTransform", arguments)}});
framevm.toolsFunc.defineProperty(OffscreenCanvasRenderingContext2D.prototype, "stroke", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "stroke", arguments)}});
framevm.toolsFunc.defineProperty(OffscreenCanvasRenderingContext2D.prototype, "strokeText", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "strokeText", arguments)}});
framevm.toolsFunc.defineProperty(OffscreenCanvasRenderingContext2D.prototype, "transform", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "transform", arguments)}});
framevm.toolsFunc.defineProperty(OffscreenCanvasRenderingContext2D.prototype, "translate", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "translate", arguments)}});
framevm.toolsFunc.defineProperty(OffscreenCanvasRenderingContext2D.prototype, "arc", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "arc", arguments)}});
framevm.toolsFunc.defineProperty(OffscreenCanvasRenderingContext2D.prototype, "arcTo", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "arcTo", arguments)}});
framevm.toolsFunc.defineProperty(OffscreenCanvasRenderingContext2D.prototype, "beginPath", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "beginPath", arguments)}});
framevm.toolsFunc.defineProperty(OffscreenCanvasRenderingContext2D.prototype, "bezierCurveTo", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "bezierCurveTo", arguments)}});
framevm.toolsFunc.defineProperty(OffscreenCanvasRenderingContext2D.prototype, "clearRect", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "clearRect", arguments)}});
framevm.toolsFunc.defineProperty(OffscreenCanvasRenderingContext2D.prototype, "closePath", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "closePath", arguments)}});
framevm.toolsFunc.defineProperty(OffscreenCanvasRenderingContext2D.prototype, "ellipse", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "ellipse", arguments)}});
framevm.toolsFunc.defineProperty(OffscreenCanvasRenderingContext2D.prototype, "fillRect", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "fillRect", arguments)}});
framevm.toolsFunc.defineProperty(OffscreenCanvasRenderingContext2D.prototype, "lineTo", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "lineTo", arguments)}});
framevm.toolsFunc.defineProperty(OffscreenCanvasRenderingContext2D.prototype, "moveTo", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "moveTo", arguments)}});
framevm.toolsFunc.defineProperty(OffscreenCanvasRenderingContext2D.prototype, "quadraticCurveTo", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "quadraticCurveTo", arguments)}});
framevm.toolsFunc.defineProperty(OffscreenCanvasRenderingContext2D.prototype, "rect", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "rect", arguments)}});
framevm.toolsFunc.defineProperty(OffscreenCanvasRenderingContext2D.prototype, "resetTransform", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "resetTransform", arguments)}});
framevm.toolsFunc.defineProperty(OffscreenCanvasRenderingContext2D.prototype, "restore", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "restore", arguments)}});
framevm.toolsFunc.defineProperty(OffscreenCanvasRenderingContext2D.prototype, "rotate", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "rotate", arguments)}});
framevm.toolsFunc.defineProperty(OffscreenCanvasRenderingContext2D.prototype, "strokeRect", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, OffscreenCanvasRenderingContext2D.prototype, "OffscreenCanvasRenderingContext2D", "strokeRect", arguments)}});
