// PaymentAddress 对象 
PaymentAddress = function PaymentAddress(){return framevm.toolsFunc.throwError("TypeError", "Illegal constructor");};
framevm.toolsFunc.safeProto(PaymentAddress,"PaymentAddress");
framevm.toolsFunc.defineProperty(PaymentAddress.prototype, "city", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, PaymentAddress.prototype, "PaymentAddress", "city_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(PaymentAddress.prototype, "country", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, PaymentAddress.prototype, "PaymentAddress", "country_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(PaymentAddress.prototype, "dependentLocality", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, PaymentAddress.prototype, "PaymentAddress", "dependentLocality_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(PaymentAddress.prototype, "organization", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, PaymentAddress.prototype, "PaymentAddress", "organization_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(PaymentAddress.prototype, "phone", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, PaymentAddress.prototype, "PaymentAddress", "phone_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(PaymentAddress.prototype, "postalCode", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, PaymentAddress.prototype, "PaymentAddress", "postalCode_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(PaymentAddress.prototype, "recipient", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, PaymentAddress.prototype, "PaymentAddress", "recipient_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(PaymentAddress.prototype, "region", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, PaymentAddress.prototype, "PaymentAddress", "region_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(PaymentAddress.prototype, "sortingCode", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, PaymentAddress.prototype, "PaymentAddress", "sortingCode_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(PaymentAddress.prototype, "addressLine", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, PaymentAddress.prototype, "PaymentAddress", "addressLine_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(PaymentAddress.prototype, "toJSON", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, PaymentAddress.prototype, "PaymentAddress", "toJSON", arguments)}});
