// PaymentRequest 对象 
PaymentRequest = function PaymentRequest(){return framevm.toolsFunc.throwError("TypeError", "Failed to construct 'PaymentRequest': 1 argument required, but only 0 present.");};
framevm.toolsFunc.safeProto(PaymentRequest,"PaymentRequest");
Object.setPrototypeOf(PaymentRequest.prototype, EventTarget.prototype);
framevm.toolsFunc.defineProperty(PaymentRequest.prototype, "id", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, PaymentRequest.prototype, "PaymentRequest", "id_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(PaymentRequest.prototype, "shippingAddress", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, PaymentRequest.prototype, "PaymentRequest", "shippingAddress_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(PaymentRequest.prototype, "shippingOption", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, PaymentRequest.prototype, "PaymentRequest", "shippingOption_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(PaymentRequest.prototype, "shippingType", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, PaymentRequest.prototype, "PaymentRequest", "shippingType_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(PaymentRequest.prototype, "onshippingaddresschange", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, PaymentRequest.prototype, "PaymentRequest", "onshippingaddresschange_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, PaymentRequest.prototype, "PaymentRequest", "onshippingaddresschange_set", arguments)}});
framevm.toolsFunc.defineProperty(PaymentRequest.prototype, "onshippingoptionchange", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, PaymentRequest.prototype, "PaymentRequest", "onshippingoptionchange_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, PaymentRequest.prototype, "PaymentRequest", "onshippingoptionchange_set", arguments)}});
framevm.toolsFunc.defineProperty(PaymentRequest.prototype, "abort", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, PaymentRequest.prototype, "PaymentRequest", "abort", arguments)}});
framevm.toolsFunc.defineProperty(PaymentRequest.prototype, "canMakePayment", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, PaymentRequest.prototype, "PaymentRequest", "canMakePayment", arguments)}});
framevm.toolsFunc.defineProperty(PaymentRequest.prototype, "hasEnrolledInstrument", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, PaymentRequest.prototype, "PaymentRequest", "hasEnrolledInstrument", arguments)}});
framevm.toolsFunc.defineProperty(PaymentRequest.prototype, "show", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, PaymentRequest.prototype, "PaymentRequest", "show", arguments)}});
framevm.toolsFunc.defineProperty(PaymentRequest.prototype, "onpaymentmethodchange", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, PaymentRequest.prototype, "PaymentRequest", "onpaymentmethodchange_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, PaymentRequest.prototype, "PaymentRequest", "onpaymentmethodchange_set", arguments)}});
