// PaymentResponse 对象 
PaymentResponse = function PaymentResponse(){return framevm.toolsFunc.throwError("TypeError", "Illegal constructor");};
framevm.toolsFunc.safeProto(PaymentResponse,"PaymentResponse");
Object.setPrototypeOf(PaymentResponse.prototype, EventTarget.prototype);
framevm.toolsFunc.defineProperty(PaymentResponse.prototype, "requestId", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, PaymentResponse.prototype, "PaymentResponse", "requestId_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(PaymentResponse.prototype, "methodName", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, PaymentResponse.prototype, "PaymentResponse", "methodName_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(PaymentResponse.prototype, "details", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, PaymentResponse.prototype, "PaymentResponse", "details_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(PaymentResponse.prototype, "shippingAddress", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, PaymentResponse.prototype, "PaymentResponse", "shippingAddress_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(PaymentResponse.prototype, "shippingOption", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, PaymentResponse.prototype, "PaymentResponse", "shippingOption_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(PaymentResponse.prototype, "payerName", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, PaymentResponse.prototype, "PaymentResponse", "payerName_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(PaymentResponse.prototype, "payerEmail", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, PaymentResponse.prototype, "PaymentResponse", "payerEmail_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(PaymentResponse.prototype, "payerPhone", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, PaymentResponse.prototype, "PaymentResponse", "payerPhone_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(PaymentResponse.prototype, "onpayerdetailchange", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, PaymentResponse.prototype, "PaymentResponse", "onpayerdetailchange_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, PaymentResponse.prototype, "PaymentResponse", "onpayerdetailchange_set", arguments)}});
framevm.toolsFunc.defineProperty(PaymentResponse.prototype, "complete", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, PaymentResponse.prototype, "PaymentResponse", "complete", arguments)}});
framevm.toolsFunc.defineProperty(PaymentResponse.prototype, "retry", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, PaymentResponse.prototype, "PaymentResponse", "retry", arguments)}});
framevm.toolsFunc.defineProperty(PaymentResponse.prototype, "toJSON", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, PaymentResponse.prototype, "PaymentResponse", "toJSON", arguments)}});
