// PerformanceNavigationTiming 对象 
PerformanceNavigationTiming = function PerformanceNavigationTiming(){return framevm.toolsFunc.throwError("TypeError", "Illegal constructor");};
framevm.toolsFunc.safeProto(PerformanceNavigationTiming,"PerformanceNavigationTiming");
Object.setPrototypeOf(PerformanceNavigationTiming.prototype, PerformanceResourceTiming.prototype);
framevm.toolsFunc.defineProperty(PerformanceNavigationTiming.prototype, "unloadEventStart", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, PerformanceNavigationTiming.prototype, "PerformanceNavigationTiming", "unloadEventStart_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(PerformanceNavigationTiming.prototype, "unloadEventEnd", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, PerformanceNavigationTiming.prototype, "PerformanceNavigationTiming", "unloadEventEnd_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(PerformanceNavigationTiming.prototype, "domInteractive", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, PerformanceNavigationTiming.prototype, "PerformanceNavigationTiming", "domInteractive_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(PerformanceNavigationTiming.prototype, "domContentLoadedEventStart", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, PerformanceNavigationTiming.prototype, "PerformanceNavigationTiming", "domContentLoadedEventStart_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(PerformanceNavigationTiming.prototype, "domContentLoadedEventEnd", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, PerformanceNavigationTiming.prototype, "PerformanceNavigationTiming", "domContentLoadedEventEnd_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(PerformanceNavigationTiming.prototype, "domComplete", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, PerformanceNavigationTiming.prototype, "PerformanceNavigationTiming", "domComplete_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(PerformanceNavigationTiming.prototype, "loadEventStart", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, PerformanceNavigationTiming.prototype, "PerformanceNavigationTiming", "loadEventStart_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(PerformanceNavigationTiming.prototype, "loadEventEnd", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, PerformanceNavigationTiming.prototype, "PerformanceNavigationTiming", "loadEventEnd_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(PerformanceNavigationTiming.prototype, "type", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, PerformanceNavigationTiming.prototype, "PerformanceNavigationTiming", "type_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(PerformanceNavigationTiming.prototype, "redirectCount", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, PerformanceNavigationTiming.prototype, "PerformanceNavigationTiming", "redirectCount_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(PerformanceNavigationTiming.prototype, "toJSON", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, PerformanceNavigationTiming.prototype, "PerformanceNavigationTiming", "toJSON", arguments)}});
framevm.toolsFunc.defineProperty(PerformanceNavigationTiming.prototype, "activationStart", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, PerformanceNavigationTiming.prototype, "PerformanceNavigationTiming", "activationStart_get", arguments)}, set:undefined});
