// PerformanceResourceTiming 对象 
PerformanceResourceTiming = function PerformanceResourceTiming(){return framevm.toolsFunc.throwError("TypeError", "Illegal constructor");};
framevm.toolsFunc.safeProto(PerformanceResourceTiming,"PerformanceResourceTiming");
Object.setPrototypeOf(PerformanceResourceTiming.prototype, PerformanceEntry.prototype);
framevm.toolsFunc.defineProperty(PerformanceResourceTiming.prototype, "initiatorType", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, PerformanceResourceTiming.prototype, "PerformanceResourceTiming", "initiatorType_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(PerformanceResourceTiming.prototype, "nextHopProtocol", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, PerformanceResourceTiming.prototype, "PerformanceResourceTiming", "nextHopProtocol_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(PerformanceResourceTiming.prototype, "workerStart", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, PerformanceResourceTiming.prototype, "PerformanceResourceTiming", "workerStart_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(PerformanceResourceTiming.prototype, "redirectStart", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, PerformanceResourceTiming.prototype, "PerformanceResourceTiming", "redirectStart_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(PerformanceResourceTiming.prototype, "redirectEnd", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, PerformanceResourceTiming.prototype, "PerformanceResourceTiming", "redirectEnd_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(PerformanceResourceTiming.prototype, "fetchStart", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, PerformanceResourceTiming.prototype, "PerformanceResourceTiming", "fetchStart_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(PerformanceResourceTiming.prototype, "domainLookupStart", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, PerformanceResourceTiming.prototype, "PerformanceResourceTiming", "domainLookupStart_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(PerformanceResourceTiming.prototype, "domainLookupEnd", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, PerformanceResourceTiming.prototype, "PerformanceResourceTiming", "domainLookupEnd_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(PerformanceResourceTiming.prototype, "connectStart", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, PerformanceResourceTiming.prototype, "PerformanceResourceTiming", "connectStart_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(PerformanceResourceTiming.prototype, "connectEnd", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, PerformanceResourceTiming.prototype, "PerformanceResourceTiming", "connectEnd_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(PerformanceResourceTiming.prototype, "secureConnectionStart", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, PerformanceResourceTiming.prototype, "PerformanceResourceTiming", "secureConnectionStart_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(PerformanceResourceTiming.prototype, "requestStart", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, PerformanceResourceTiming.prototype, "PerformanceResourceTiming", "requestStart_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(PerformanceResourceTiming.prototype, "responseStart", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, PerformanceResourceTiming.prototype, "PerformanceResourceTiming", "responseStart_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(PerformanceResourceTiming.prototype, "responseEnd", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, PerformanceResourceTiming.prototype, "PerformanceResourceTiming", "responseEnd_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(PerformanceResourceTiming.prototype, "transferSize", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, PerformanceResourceTiming.prototype, "PerformanceResourceTiming", "transferSize_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(PerformanceResourceTiming.prototype, "encodedBodySize", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, PerformanceResourceTiming.prototype, "PerformanceResourceTiming", "encodedBodySize_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(PerformanceResourceTiming.prototype, "decodedBodySize", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, PerformanceResourceTiming.prototype, "PerformanceResourceTiming", "decodedBodySize_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(PerformanceResourceTiming.prototype, "serverTiming", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, PerformanceResourceTiming.prototype, "PerformanceResourceTiming", "serverTiming_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(PerformanceResourceTiming.prototype, "toJSON", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, PerformanceResourceTiming.prototype, "PerformanceResourceTiming", "toJSON", arguments)}});
framevm.toolsFunc.defineProperty(PerformanceResourceTiming.prototype, "renderBlockingStatus", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, PerformanceResourceTiming.prototype, "PerformanceResourceTiming", "renderBlockingStatus_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(PerformanceResourceTiming.prototype, "responseStatus", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, PerformanceResourceTiming.prototype, "PerformanceResourceTiming", "responseStatus_get", arguments)}, set:undefined});
