// PresentationConnection 对象 
PresentationConnection = function PresentationConnection(){return framevm.toolsFunc.throwError("TypeError", "Illegal constructor");};
framevm.toolsFunc.safeProto(PresentationConnection,"PresentationConnection");
Object.setPrototypeOf(PresentationConnection.prototype, EventTarget.prototype);
framevm.toolsFunc.defineProperty(PresentationConnection.prototype, "id", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, PresentationConnection.prototype, "PresentationConnection", "id_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(PresentationConnection.prototype, "url", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, PresentationConnection.prototype, "PresentationConnection", "url_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(PresentationConnection.prototype, "state", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, PresentationConnection.prototype, "PresentationConnection", "state_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(PresentationConnection.prototype, "onconnect", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, PresentationConnection.prototype, "PresentationConnection", "onconnect_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, PresentationConnection.prototype, "PresentationConnection", "onconnect_set", arguments)}});
framevm.toolsFunc.defineProperty(PresentationConnection.prototype, "onclose", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, PresentationConnection.prototype, "PresentationConnection", "onclose_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, PresentationConnection.prototype, "PresentationConnection", "onclose_set", arguments)}});
framevm.toolsFunc.defineProperty(PresentationConnection.prototype, "onterminate", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, PresentationConnection.prototype, "PresentationConnection", "onterminate_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, PresentationConnection.prototype, "PresentationConnection", "onterminate_set", arguments)}});
framevm.toolsFunc.defineProperty(PresentationConnection.prototype, "binaryType", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, PresentationConnection.prototype, "PresentationConnection", "binaryType_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, PresentationConnection.prototype, "PresentationConnection", "binaryType_set", arguments)}});
framevm.toolsFunc.defineProperty(PresentationConnection.prototype, "onmessage", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, PresentationConnection.prototype, "PresentationConnection", "onmessage_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, PresentationConnection.prototype, "PresentationConnection", "onmessage_set", arguments)}});
framevm.toolsFunc.defineProperty(PresentationConnection.prototype, "close", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, PresentationConnection.prototype, "PresentationConnection", "close", arguments)}});
framevm.toolsFunc.defineProperty(PresentationConnection.prototype, "send", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, PresentationConnection.prototype, "PresentationConnection", "send", arguments)}});
framevm.toolsFunc.defineProperty(PresentationConnection.prototype, "terminate", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, PresentationConnection.prototype, "PresentationConnection", "terminate", arguments)}});
