// RTCIceCandidate 对象 
RTCIceCandidate = function RTCIceCandidate(){return framevm.toolsFunc.throwError("TypeError", "Failed to construct 'RTCIceCandidate': sdpMid and sdpMLineIndex are both null.");};
framevm.toolsFunc.safeProto(RTCIceCandidate,"RTCIceCandidate");
framevm.toolsFunc.defineProperty(RTCIceCandidate.prototype, "candidate", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, RTCIceCandidate.prototype, "RTCIceCandidate", "candidate_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(RTCIceCandidate.prototype, "sdpMid", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, RTCIceCandidate.prototype, "RTCIceCandidate", "sdpMid_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(RTCIceCandidate.prototype, "sdpMLineIndex", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, RTCIceCandidate.prototype, "RTCIceCandidate", "sdpMLineIndex_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(RTCIceCandidate.prototype, "foundation", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, RTCIceCandidate.prototype, "RTCIceCandidate", "foundation_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(RTCIceCandidate.prototype, "component", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, RTCIceCandidate.prototype, "RTCIceCandidate", "component_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(RTCIceCandidate.prototype, "priority", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, RTCIceCandidate.prototype, "RTCIceCandidate", "priority_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(RTCIceCandidate.prototype, "address", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, RTCIceCandidate.prototype, "RTCIceCandidate", "address_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(RTCIceCandidate.prototype, "protocol", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, RTCIceCandidate.prototype, "RTCIceCandidate", "protocol_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(RTCIceCandidate.prototype, "port", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, RTCIceCandidate.prototype, "RTCIceCandidate", "port_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(RTCIceCandidate.prototype, "type", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, RTCIceCandidate.prototype, "RTCIceCandidate", "type_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(RTCIceCandidate.prototype, "tcpType", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, RTCIceCandidate.prototype, "RTCIceCandidate", "tcpType_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(RTCIceCandidate.prototype, "relatedAddress", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, RTCIceCandidate.prototype, "RTCIceCandidate", "relatedAddress_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(RTCIceCandidate.prototype, "relatedPort", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, RTCIceCandidate.prototype, "RTCIceCandidate", "relatedPort_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(RTCIceCandidate.prototype, "usernameFragment", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, RTCIceCandidate.prototype, "RTCIceCandidate", "usernameFragment_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(RTCIceCandidate.prototype, "toJSON", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, RTCIceCandidate.prototype, "RTCIceCandidate", "toJSON", arguments)}});
