// RTCPeerConnectionIceErrorEvent 对象 
RTCPeerConnectionIceErrorEvent = function RTCPeerConnectionIceErrorEvent(){return framevm.toolsFunc.throwError("TypeError", "Failed to construct 'RTCPeerConnectionIceErrorEvent': 2 arguments required, but only 0 present.");};
framevm.toolsFunc.safeProto(RTCPeerConnectionIceErrorEvent,"RTCPeerConnectionIceErrorEvent");
Object.setPrototypeOf(RTCPeerConnectionIceErrorEvent.prototype, Event.prototype);
framevm.toolsFunc.defineProperty(RTCPeerConnectionIceErrorEvent.prototype, "address", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, RTCPeerConnectionIceErrorEvent.prototype, "RTCPeerConnectionIceErrorEvent", "address_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(RTCPeerConnectionIceErrorEvent.prototype, "port", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, RTCPeerConnectionIceErrorEvent.prototype, "RTCPeerConnectionIceErrorEvent", "port_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(RTCPeerConnectionIceErrorEvent.prototype, "hostCandidate", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, RTCPeerConnectionIceErrorEvent.prototype, "RTCPeerConnectionIceErrorEvent", "hostCandidate_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(RTCPeerConnectionIceErrorEvent.prototype, "url", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, RTCPeerConnectionIceErrorEvent.prototype, "RTCPeerConnectionIceErrorEvent", "url_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(RTCPeerConnectionIceErrorEvent.prototype, "errorCode", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, RTCPeerConnectionIceErrorEvent.prototype, "RTCPeerConnectionIceErrorEvent", "errorCode_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(RTCPeerConnectionIceErrorEvent.prototype, "errorText", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, RTCPeerConnectionIceErrorEvent.prototype, "RTCPeerConnectionIceErrorEvent", "errorText_get", arguments)}, set:undefined});
