// RTCRtpTransceiver 对象 
RTCRtpTransceiver = function RTCRtpTransceiver(){return framevm.toolsFunc.throwError("TypeError", "Illegal constructor");};
framevm.toolsFunc.safeProto(RTCRtpTransceiver,"RTCRtpTransceiver");
framevm.toolsFunc.defineProperty(RTCRtpTransceiver.prototype, "mid", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, RTCRtpTransceiver.prototype, "RTCRtpTransceiver", "mid_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(RTCRtpTransceiver.prototype, "sender", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, RTCRtpTransceiver.prototype, "RTCRtpTransceiver", "sender_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(RTCRtpTransceiver.prototype, "receiver", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, RTCRtpTransceiver.prototype, "RTCRtpTransceiver", "receiver_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(RTCRtpTransceiver.prototype, "stopped", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, RTCRtpTransceiver.prototype, "RTCRtpTransceiver", "stopped_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(RTCRtpTransceiver.prototype, "direction", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, RTCRtpTransceiver.prototype, "RTCRtpTransceiver", "direction_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, RTCRtpTransceiver.prototype, "RTCRtpTransceiver", "direction_set", arguments)}});
framevm.toolsFunc.defineProperty(RTCRtpTransceiver.prototype, "currentDirection", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, RTCRtpTransceiver.prototype, "RTCRtpTransceiver", "currentDirection_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(RTCRtpTransceiver.prototype, "setCodecPreferences", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, RTCRtpTransceiver.prototype, "RTCRtpTransceiver", "setCodecPreferences", arguments)}});
framevm.toolsFunc.defineProperty(RTCRtpTransceiver.prototype, "stop", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, RTCRtpTransceiver.prototype, "RTCRtpTransceiver", "stop", arguments)}});
