// SecurityPolicyViolationEvent 对象 
SecurityPolicyViolationEvent = function SecurityPolicyViolationEvent(){return framevm.toolsFunc.throwError("TypeError", "Failed to construct 'SecurityPolicyViolationEvent': 1 argument required, but only 0 present.");};
framevm.toolsFunc.safeProto(SecurityPolicyViolationEvent,"SecurityPolicyViolationEvent");
Object.setPrototypeOf(SecurityPolicyViolationEvent.prototype, Event.prototype);
framevm.toolsFunc.defineProperty(SecurityPolicyViolationEvent.prototype, "documentURI", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SecurityPolicyViolationEvent.prototype, "SecurityPolicyViolationEvent", "documentURI_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SecurityPolicyViolationEvent.prototype, "referrer", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SecurityPolicyViolationEvent.prototype, "SecurityPolicyViolationEvent", "referrer_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SecurityPolicyViolationEvent.prototype, "blockedURI", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SecurityPolicyViolationEvent.prototype, "SecurityPolicyViolationEvent", "blockedURI_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SecurityPolicyViolationEvent.prototype, "violatedDirective", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SecurityPolicyViolationEvent.prototype, "SecurityPolicyViolationEvent", "violatedDirective_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SecurityPolicyViolationEvent.prototype, "effectiveDirective", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SecurityPolicyViolationEvent.prototype, "SecurityPolicyViolationEvent", "effectiveDirective_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SecurityPolicyViolationEvent.prototype, "originalPolicy", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SecurityPolicyViolationEvent.prototype, "SecurityPolicyViolationEvent", "originalPolicy_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SecurityPolicyViolationEvent.prototype, "disposition", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SecurityPolicyViolationEvent.prototype, "SecurityPolicyViolationEvent", "disposition_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SecurityPolicyViolationEvent.prototype, "sourceFile", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SecurityPolicyViolationEvent.prototype, "SecurityPolicyViolationEvent", "sourceFile_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SecurityPolicyViolationEvent.prototype, "statusCode", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SecurityPolicyViolationEvent.prototype, "SecurityPolicyViolationEvent", "statusCode_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SecurityPolicyViolationEvent.prototype, "lineNumber", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SecurityPolicyViolationEvent.prototype, "SecurityPolicyViolationEvent", "lineNumber_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SecurityPolicyViolationEvent.prototype, "columnNumber", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SecurityPolicyViolationEvent.prototype, "SecurityPolicyViolationEvent", "columnNumber_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SecurityPolicyViolationEvent.prototype, "sample", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SecurityPolicyViolationEvent.prototype, "SecurityPolicyViolationEvent", "sample_get", arguments)}, set:undefined});
