// ServiceWorkerRegistration 对象 
ServiceWorkerRegistration = function ServiceWorkerRegistration(){return framevm.toolsFunc.throwError("TypeError", "Illegal constructor");};
framevm.toolsFunc.safeProto(ServiceWorkerRegistration,"ServiceWorkerRegistration");
Object.setPrototypeOf(ServiceWorkerRegistration.prototype, EventTarget.prototype);
framevm.toolsFunc.defineProperty(ServiceWorkerRegistration.prototype, "installing", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ServiceWorkerRegistration.prototype, "ServiceWorkerRegistration", "installing_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(ServiceWorkerRegistration.prototype, "waiting", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ServiceWorkerRegistration.prototype, "ServiceWorkerRegistration", "waiting_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(ServiceWorkerRegistration.prototype, "active", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ServiceWorkerRegistration.prototype, "ServiceWorkerRegistration", "active_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(ServiceWorkerRegistration.prototype, "navigationPreload", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ServiceWorkerRegistration.prototype, "ServiceWorkerRegistration", "navigationPreload_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(ServiceWorkerRegistration.prototype, "scope", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ServiceWorkerRegistration.prototype, "ServiceWorkerRegistration", "scope_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(ServiceWorkerRegistration.prototype, "updateViaCache", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ServiceWorkerRegistration.prototype, "ServiceWorkerRegistration", "updateViaCache_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(ServiceWorkerRegistration.prototype, "onupdatefound", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ServiceWorkerRegistration.prototype, "ServiceWorkerRegistration", "onupdatefound_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, ServiceWorkerRegistration.prototype, "ServiceWorkerRegistration", "onupdatefound_set", arguments)}});
framevm.toolsFunc.defineProperty(ServiceWorkerRegistration.prototype, "unregister", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, ServiceWorkerRegistration.prototype, "ServiceWorkerRegistration", "unregister", arguments)}});
framevm.toolsFunc.defineProperty(ServiceWorkerRegistration.prototype, "update", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, ServiceWorkerRegistration.prototype, "ServiceWorkerRegistration", "update", arguments)}});
framevm.toolsFunc.defineProperty(ServiceWorkerRegistration.prototype, "paymentManager", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ServiceWorkerRegistration.prototype, "ServiceWorkerRegistration", "paymentManager_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(ServiceWorkerRegistration.prototype, "backgroundFetch", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ServiceWorkerRegistration.prototype, "ServiceWorkerRegistration", "backgroundFetch_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(ServiceWorkerRegistration.prototype, "periodicSync", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ServiceWorkerRegistration.prototype, "ServiceWorkerRegistration", "periodicSync_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(ServiceWorkerRegistration.prototype, "sync", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ServiceWorkerRegistration.prototype, "ServiceWorkerRegistration", "sync_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(ServiceWorkerRegistration.prototype, "cookies", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ServiceWorkerRegistration.prototype, "ServiceWorkerRegistration", "cookies_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(ServiceWorkerRegistration.prototype, "pushManager", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ServiceWorkerRegistration.prototype, "ServiceWorkerRegistration", "pushManager_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(ServiceWorkerRegistration.prototype, "getNotifications", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, ServiceWorkerRegistration.prototype, "ServiceWorkerRegistration", "getNotifications", arguments)}});
framevm.toolsFunc.defineProperty(ServiceWorkerRegistration.prototype, "showNotification", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, ServiceWorkerRegistration.prototype, "ServiceWorkerRegistration", "showNotification", arguments)}});
