// ServiceWorkerContainer 对象
ServiceWorkerContainer = function ServiceWorkerContainer(){return framevm.toolsFunc.throwError("TypeError", "Illegal constructor");};
framevm.toolsFunc.safeProto(ServiceWorkerContainer,"ServiceWorkerContainer");
Object.setPrototypeOf(ServiceWorkerContainer.prototype, EventTarget.prototype);
framevm.toolsFunc.defineProperty(ServiceWorkerContainer.prototype, "controller", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ServiceWorkerContainer.prototype, "ServiceWorkerContainer", "controller_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(ServiceWorkerContainer.prototype, "ready", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ServiceWorkerContainer.prototype, "ServiceWorkerContainer", "ready_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(ServiceWorkerContainer.prototype, "oncontrollerchange", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ServiceWorkerContainer.prototype, "ServiceWorkerContainer", "oncontrollerchange_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, ServiceWorkerContainer.prototype, "ServiceWorkerContainer", "oncontrollerchange_set", arguments)}});
framevm.toolsFunc.defineProperty(ServiceWorkerContainer.prototype, "onmessage", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ServiceWorkerContainer.prototype, "ServiceWorkerContainer", "onmessage_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, ServiceWorkerContainer.prototype, "ServiceWorkerContainer", "onmessage_set", arguments)}});
framevm.toolsFunc.defineProperty(ServiceWorkerContainer.prototype, "onmessageerror", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ServiceWorkerContainer.prototype, "ServiceWorkerContainer", "onmessageerror_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, ServiceWorkerContainer.prototype, "ServiceWorkerContainer", "onmessageerror_set", arguments)}});
framevm.toolsFunc.defineProperty(ServiceWorkerContainer.prototype, "getRegistration", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, ServiceWorkerContainer.prototype, "ServiceWorkerContainer", "getRegistration", arguments)}});
framevm.toolsFunc.defineProperty(ServiceWorkerContainer.prototype, "getRegistrations", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, ServiceWorkerContainer.prototype, "ServiceWorkerContainer", "getRegistrations", arguments)}});
framevm.toolsFunc.defineProperty(ServiceWorkerContainer.prototype, "register", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, ServiceWorkerContainer.prototype, "ServiceWorkerContainer", "register", arguments)}});
framevm.toolsFunc.defineProperty(ServiceWorkerContainer.prototype, "startMessages", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, ServiceWorkerContainer.prototype, "ServiceWorkerContainer", "startMessages", arguments)}});
