// ShadowRoot 对象 
ShadowRoot = function ShadowRoot(){return framevm.toolsFunc.throwError("TypeError", "Illegal constructor");};
framevm.toolsFunc.safeProto(ShadowRoot,"ShadowRoot");
Object.setPrototypeOf(ShadowRoot.prototype, DocumentFragment.prototype);
framevm.toolsFunc.defineProperty(ShadowRoot.prototype, "mode", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ShadowRoot.prototype, "ShadowRoot", "mode_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(ShadowRoot.prototype, "host", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ShadowRoot.prototype, "ShadowRoot", "host_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(ShadowRoot.prototype, "onslotchange", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ShadowRoot.prototype, "ShadowRoot", "onslotchange_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, ShadowRoot.prototype, "ShadowRoot", "onslotchange_set", arguments)}});
framevm.toolsFunc.defineProperty(ShadowRoot.prototype, "innerHTML", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ShadowRoot.prototype, "ShadowRoot", "innerHTML_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, ShadowRoot.prototype, "ShadowRoot", "innerHTML_set", arguments)}});
framevm.toolsFunc.defineProperty(ShadowRoot.prototype, "delegatesFocus", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ShadowRoot.prototype, "ShadowRoot", "delegatesFocus_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(ShadowRoot.prototype, "slotAssignment", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ShadowRoot.prototype, "ShadowRoot", "slotAssignment_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(ShadowRoot.prototype, "pictureInPictureElement", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ShadowRoot.prototype, "ShadowRoot", "pictureInPictureElement_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(ShadowRoot.prototype, "activeElement", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ShadowRoot.prototype, "ShadowRoot", "activeElement_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(ShadowRoot.prototype, "styleSheets", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ShadowRoot.prototype, "ShadowRoot", "styleSheets_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(ShadowRoot.prototype, "pointerLockElement", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ShadowRoot.prototype, "ShadowRoot", "pointerLockElement_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(ShadowRoot.prototype, "fullscreenElement", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ShadowRoot.prototype, "ShadowRoot", "fullscreenElement_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, ShadowRoot.prototype, "ShadowRoot", "fullscreenElement_set", arguments)}});
framevm.toolsFunc.defineProperty(ShadowRoot.prototype, "adoptedStyleSheets", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ShadowRoot.prototype, "ShadowRoot", "adoptedStyleSheets_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, ShadowRoot.prototype, "ShadowRoot", "adoptedStyleSheets_set", arguments)}});
framevm.toolsFunc.defineProperty(ShadowRoot.prototype, "elementFromPoint", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, ShadowRoot.prototype, "ShadowRoot", "elementFromPoint", arguments)}});
framevm.toolsFunc.defineProperty(ShadowRoot.prototype, "elementsFromPoint", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, ShadowRoot.prototype, "ShadowRoot", "elementsFromPoint", arguments)}});
framevm.toolsFunc.defineProperty(ShadowRoot.prototype, "getInnerHTML", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, ShadowRoot.prototype, "ShadowRoot", "getInnerHTML", arguments)}});
framevm.toolsFunc.defineProperty(ShadowRoot.prototype, "getSelection", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, ShadowRoot.prototype, "ShadowRoot", "getSelection", arguments)}});
framevm.toolsFunc.defineProperty(ShadowRoot.prototype, "getAnimations", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, ShadowRoot.prototype, "ShadowRoot", "getAnimations", arguments)}});
