// SourceBuffer 对象 
SourceBuffer = function SourceBuffer(){return framevm.toolsFunc.throwError("TypeError", "Illegal constructor");};
framevm.toolsFunc.safeProto(SourceBuffer,"SourceBuffer");
Object.setPrototypeOf(SourceBuffer.prototype, EventTarget.prototype);
framevm.toolsFunc.defineProperty(SourceBuffer.prototype, "mode", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SourceBuffer.prototype, "SourceBuffer", "mode_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, SourceBuffer.prototype, "SourceBuffer", "mode_set", arguments)}});
framevm.toolsFunc.defineProperty(SourceBuffer.prototype, "updating", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SourceBuffer.prototype, "SourceBuffer", "updating_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SourceBuffer.prototype, "buffered", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SourceBuffer.prototype, "SourceBuffer", "buffered_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SourceBuffer.prototype, "timestampOffset", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SourceBuffer.prototype, "SourceBuffer", "timestampOffset_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, SourceBuffer.prototype, "SourceBuffer", "timestampOffset_set", arguments)}});
framevm.toolsFunc.defineProperty(SourceBuffer.prototype, "appendWindowStart", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SourceBuffer.prototype, "SourceBuffer", "appendWindowStart_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, SourceBuffer.prototype, "SourceBuffer", "appendWindowStart_set", arguments)}});
framevm.toolsFunc.defineProperty(SourceBuffer.prototype, "appendWindowEnd", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SourceBuffer.prototype, "SourceBuffer", "appendWindowEnd_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, SourceBuffer.prototype, "SourceBuffer", "appendWindowEnd_set", arguments)}});
framevm.toolsFunc.defineProperty(SourceBuffer.prototype, "onupdatestart", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SourceBuffer.prototype, "SourceBuffer", "onupdatestart_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, SourceBuffer.prototype, "SourceBuffer", "onupdatestart_set", arguments)}});
framevm.toolsFunc.defineProperty(SourceBuffer.prototype, "onupdate", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SourceBuffer.prototype, "SourceBuffer", "onupdate_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, SourceBuffer.prototype, "SourceBuffer", "onupdate_set", arguments)}});
framevm.toolsFunc.defineProperty(SourceBuffer.prototype, "onupdateend", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SourceBuffer.prototype, "SourceBuffer", "onupdateend_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, SourceBuffer.prototype, "SourceBuffer", "onupdateend_set", arguments)}});
framevm.toolsFunc.defineProperty(SourceBuffer.prototype, "onerror", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SourceBuffer.prototype, "SourceBuffer", "onerror_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, SourceBuffer.prototype, "SourceBuffer", "onerror_set", arguments)}});
framevm.toolsFunc.defineProperty(SourceBuffer.prototype, "onabort", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SourceBuffer.prototype, "SourceBuffer", "onabort_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, SourceBuffer.prototype, "SourceBuffer", "onabort_set", arguments)}});
framevm.toolsFunc.defineProperty(SourceBuffer.prototype, "abort", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, SourceBuffer.prototype, "SourceBuffer", "abort", arguments)}});
framevm.toolsFunc.defineProperty(SourceBuffer.prototype, "appendBuffer", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, SourceBuffer.prototype, "SourceBuffer", "appendBuffer", arguments)}});
framevm.toolsFunc.defineProperty(SourceBuffer.prototype, "changeType", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, SourceBuffer.prototype, "SourceBuffer", "changeType", arguments)}});
framevm.toolsFunc.defineProperty(SourceBuffer.prototype, "remove", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, SourceBuffer.prototype, "SourceBuffer", "remove", arguments)}});
