// SpeechSynthesisUtterance 对象 
SpeechSynthesisUtterance = function SpeechSynthesisUtterance(){};
framevm.toolsFunc.safeProto(SpeechSynthesisUtterance,"SpeechSynthesisUtterance");
Object.setPrototypeOf(SpeechSynthesisUtterance.prototype, EventTarget.prototype);
framevm.toolsFunc.defineProperty(SpeechSynthesisUtterance.prototype, "text", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SpeechSynthesisUtterance.prototype, "SpeechSynthesisUtterance", "text_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, SpeechSynthesisUtterance.prototype, "SpeechSynthesisUtterance", "text_set", arguments)}});
framevm.toolsFunc.defineProperty(SpeechSynthesisUtterance.prototype, "lang", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SpeechSynthesisUtterance.prototype, "SpeechSynthesisUtterance", "lang_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, SpeechSynthesisUtterance.prototype, "SpeechSynthesisUtterance", "lang_set", arguments)}});
framevm.toolsFunc.defineProperty(SpeechSynthesisUtterance.prototype, "voice", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SpeechSynthesisUtterance.prototype, "SpeechSynthesisUtterance", "voice_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, SpeechSynthesisUtterance.prototype, "SpeechSynthesisUtterance", "voice_set", arguments)}});
framevm.toolsFunc.defineProperty(SpeechSynthesisUtterance.prototype, "volume", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SpeechSynthesisUtterance.prototype, "SpeechSynthesisUtterance", "volume_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, SpeechSynthesisUtterance.prototype, "SpeechSynthesisUtterance", "volume_set", arguments)}});
framevm.toolsFunc.defineProperty(SpeechSynthesisUtterance.prototype, "rate", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SpeechSynthesisUtterance.prototype, "SpeechSynthesisUtterance", "rate_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, SpeechSynthesisUtterance.prototype, "SpeechSynthesisUtterance", "rate_set", arguments)}});
framevm.toolsFunc.defineProperty(SpeechSynthesisUtterance.prototype, "pitch", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SpeechSynthesisUtterance.prototype, "SpeechSynthesisUtterance", "pitch_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, SpeechSynthesisUtterance.prototype, "SpeechSynthesisUtterance", "pitch_set", arguments)}});
framevm.toolsFunc.defineProperty(SpeechSynthesisUtterance.prototype, "onstart", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SpeechSynthesisUtterance.prototype, "SpeechSynthesisUtterance", "onstart_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, SpeechSynthesisUtterance.prototype, "SpeechSynthesisUtterance", "onstart_set", arguments)}});
framevm.toolsFunc.defineProperty(SpeechSynthesisUtterance.prototype, "onend", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SpeechSynthesisUtterance.prototype, "SpeechSynthesisUtterance", "onend_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, SpeechSynthesisUtterance.prototype, "SpeechSynthesisUtterance", "onend_set", arguments)}});
framevm.toolsFunc.defineProperty(SpeechSynthesisUtterance.prototype, "onerror", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SpeechSynthesisUtterance.prototype, "SpeechSynthesisUtterance", "onerror_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, SpeechSynthesisUtterance.prototype, "SpeechSynthesisUtterance", "onerror_set", arguments)}});
framevm.toolsFunc.defineProperty(SpeechSynthesisUtterance.prototype, "onpause", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SpeechSynthesisUtterance.prototype, "SpeechSynthesisUtterance", "onpause_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, SpeechSynthesisUtterance.prototype, "SpeechSynthesisUtterance", "onpause_set", arguments)}});
framevm.toolsFunc.defineProperty(SpeechSynthesisUtterance.prototype, "onresume", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SpeechSynthesisUtterance.prototype, "SpeechSynthesisUtterance", "onresume_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, SpeechSynthesisUtterance.prototype, "SpeechSynthesisUtterance", "onresume_set", arguments)}});
framevm.toolsFunc.defineProperty(SpeechSynthesisUtterance.prototype, "onmark", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SpeechSynthesisUtterance.prototype, "SpeechSynthesisUtterance", "onmark_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, SpeechSynthesisUtterance.prototype, "SpeechSynthesisUtterance", "onmark_set", arguments)}});
framevm.toolsFunc.defineProperty(SpeechSynthesisUtterance.prototype, "onboundary", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SpeechSynthesisUtterance.prototype, "SpeechSynthesisUtterance", "onboundary_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, SpeechSynthesisUtterance.prototype, "SpeechSynthesisUtterance", "onboundary_set", arguments)}});
