// StylePropertyMapReadOnly 对象 
StylePropertyMapReadOnly = function StylePropertyMapReadOnly(){return framevm.toolsFunc.throwError("TypeError", "Illegal constructor");};
framevm.toolsFunc.safeProto(StylePropertyMapReadOnly,"StylePropertyMapReadOnly");
framevm.toolsFunc.defineProperty(StylePropertyMapReadOnly.prototype, "size", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, StylePropertyMapReadOnly.prototype, "StylePropertyMapReadOnly", "size_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(StylePropertyMapReadOnly.prototype, "get", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, StylePropertyMapReadOnly.prototype, "StylePropertyMapReadOnly", "get", arguments)}});
framevm.toolsFunc.defineProperty(StylePropertyMapReadOnly.prototype, "getAll", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, StylePropertyMapReadOnly.prototype, "StylePropertyMapReadOnly", "getAll", arguments)}});
framevm.toolsFunc.defineProperty(StylePropertyMapReadOnly.prototype, "has", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, StylePropertyMapReadOnly.prototype, "StylePropertyMapReadOnly", "has", arguments)}});
framevm.toolsFunc.defineProperty(StylePropertyMapReadOnly.prototype, "entries", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, StylePropertyMapReadOnly.prototype, "StylePropertyMapReadOnly", "entries", arguments)}});
framevm.toolsFunc.defineProperty(StylePropertyMapReadOnly.prototype, "forEach", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, StylePropertyMapReadOnly.prototype, "StylePropertyMapReadOnly", "forEach", arguments)}});
framevm.toolsFunc.defineProperty(StylePropertyMapReadOnly.prototype, "keys", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, StylePropertyMapReadOnly.prototype, "StylePropertyMapReadOnly", "keys", arguments)}});
framevm.toolsFunc.defineProperty(StylePropertyMapReadOnly.prototype, "values", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, StylePropertyMapReadOnly.prototype, "StylePropertyMapReadOnly", "values", arguments)}});
