// SVGAnimationElement 对象 
SVGAnimationElement = function SVGAnimationElement(){return framevm.toolsFunc.throwError("TypeError", "Illegal constructor");};
framevm.toolsFunc.safeProto(SVGAnimationElement,"SVGAnimationElement");
Object.setPrototypeOf(SVGAnimationElement.prototype, SVGElement.prototype);
framevm.toolsFunc.defineProperty(SVGAnimationElement.prototype, "targetElement", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGAnimationElement.prototype, "SVGAnimationElement", "targetElement_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SVGAnimationElement.prototype, "onbegin", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGAnimationElement.prototype, "SVGAnimationElement", "onbegin_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, SVGAnimationElement.prototype, "SVGAnimationElement", "onbegin_set", arguments)}});
framevm.toolsFunc.defineProperty(SVGAnimationElement.prototype, "onend", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGAnimationElement.prototype, "SVGAnimationElement", "onend_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, SVGAnimationElement.prototype, "SVGAnimationElement", "onend_set", arguments)}});
framevm.toolsFunc.defineProperty(SVGAnimationElement.prototype, "onrepeat", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGAnimationElement.prototype, "SVGAnimationElement", "onrepeat_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, SVGAnimationElement.prototype, "SVGAnimationElement", "onrepeat_set", arguments)}});
framevm.toolsFunc.defineProperty(SVGAnimationElement.prototype, "requiredExtensions", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGAnimationElement.prototype, "SVGAnimationElement", "requiredExtensions_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SVGAnimationElement.prototype, "systemLanguage", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGAnimationElement.prototype, "SVGAnimationElement", "systemLanguage_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SVGAnimationElement.prototype, "beginElement", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, SVGAnimationElement.prototype, "SVGAnimationElement", "beginElement", arguments)}});
framevm.toolsFunc.defineProperty(SVGAnimationElement.prototype, "beginElementAt", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, SVGAnimationElement.prototype, "SVGAnimationElement", "beginElementAt", arguments)}});
framevm.toolsFunc.defineProperty(SVGAnimationElement.prototype, "endElement", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, SVGAnimationElement.prototype, "SVGAnimationElement", "endElement", arguments)}});
framevm.toolsFunc.defineProperty(SVGAnimationElement.prototype, "endElementAt", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, SVGAnimationElement.prototype, "SVGAnimationElement", "endElementAt", arguments)}});
framevm.toolsFunc.defineProperty(SVGAnimationElement.prototype, "getCurrentTime", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, SVGAnimationElement.prototype, "SVGAnimationElement", "getCurrentTime", arguments)}});
framevm.toolsFunc.defineProperty(SVGAnimationElement.prototype, "getSimpleDuration", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, SVGAnimationElement.prototype, "SVGAnimationElement", "getSimpleDuration", arguments)}});
framevm.toolsFunc.defineProperty(SVGAnimationElement.prototype, "getStartTime", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, SVGAnimationElement.prototype, "SVGAnimationElement", "getStartTime", arguments)}});
