// SVGComponentTransferFunctionElement 对象 
SVGComponentTransferFunctionElement = function SVGComponentTransferFunctionElement(){return framevm.toolsFunc.throwError("TypeError", "Illegal constructor");};
framevm.toolsFunc.safeProto(SVGComponentTransferFunctionElement,"SVGComponentTransferFunctionElement");
Object.setPrototypeOf(SVGComponentTransferFunctionElement.prototype, SVGElement.prototype);
framevm.toolsFunc.defineProperty(SVGComponentTransferFunctionElement, "SVG_FECOMPONENTTRANSFER_TYPE_GAMMA", {configurable:false, enumerable:true, writable:false, value:5});
framevm.toolsFunc.defineProperty(SVGComponentTransferFunctionElement, "SVG_FECOMPONENTTRANSFER_TYPE_LINEAR", {configurable:false, enumerable:true, writable:false, value:4});
framevm.toolsFunc.defineProperty(SVGComponentTransferFunctionElement, "SVG_FECOMPONENTTRANSFER_TYPE_DISCRETE", {configurable:false, enumerable:true, writable:false, value:3});
framevm.toolsFunc.defineProperty(SVGComponentTransferFunctionElement, "SVG_FECOMPONENTTRANSFER_TYPE_TABLE", {configurable:false, enumerable:true, writable:false, value:2});
framevm.toolsFunc.defineProperty(SVGComponentTransferFunctionElement, "SVG_FECOMPONENTTRANSFER_TYPE_IDENTITY", {configurable:false, enumerable:true, writable:false, value:1});
framevm.toolsFunc.defineProperty(SVGComponentTransferFunctionElement, "SVG_FECOMPONENTTRANSFER_TYPE_UNKNOWN", {configurable:false, enumerable:true, writable:false, value:0});
framevm.toolsFunc.defineProperty(SVGComponentTransferFunctionElement.prototype, "SVG_FECOMPONENTTRANSFER_TYPE_GAMMA", {configurable:false, enumerable:true, writable:false, value:5});
framevm.toolsFunc.defineProperty(SVGComponentTransferFunctionElement.prototype, "SVG_FECOMPONENTTRANSFER_TYPE_LINEAR", {configurable:false, enumerable:true, writable:false, value:4});
framevm.toolsFunc.defineProperty(SVGComponentTransferFunctionElement.prototype, "SVG_FECOMPONENTTRANSFER_TYPE_DISCRETE", {configurable:false, enumerable:true, writable:false, value:3});
framevm.toolsFunc.defineProperty(SVGComponentTransferFunctionElement.prototype, "SVG_FECOMPONENTTRANSFER_TYPE_TABLE", {configurable:false, enumerable:true, writable:false, value:2});
framevm.toolsFunc.defineProperty(SVGComponentTransferFunctionElement.prototype, "SVG_FECOMPONENTTRANSFER_TYPE_IDENTITY", {configurable:false, enumerable:true, writable:false, value:1});
framevm.toolsFunc.defineProperty(SVGComponentTransferFunctionElement.prototype, "SVG_FECOMPONENTTRANSFER_TYPE_UNKNOWN", {configurable:false, enumerable:true, writable:false, value:0});
framevm.toolsFunc.defineProperty(SVGComponentTransferFunctionElement.prototype, "type", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGComponentTransferFunctionElement.prototype, "SVGComponentTransferFunctionElement", "type_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SVGComponentTransferFunctionElement.prototype, "tableValues", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGComponentTransferFunctionElement.prototype, "SVGComponentTransferFunctionElement", "tableValues_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SVGComponentTransferFunctionElement.prototype, "slope", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGComponentTransferFunctionElement.prototype, "SVGComponentTransferFunctionElement", "slope_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SVGComponentTransferFunctionElement.prototype, "intercept", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGComponentTransferFunctionElement.prototype, "SVGComponentTransferFunctionElement", "intercept_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SVGComponentTransferFunctionElement.prototype, "amplitude", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGComponentTransferFunctionElement.prototype, "SVGComponentTransferFunctionElement", "amplitude_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SVGComponentTransferFunctionElement.prototype, "exponent", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGComponentTransferFunctionElement.prototype, "SVGComponentTransferFunctionElement", "exponent_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SVGComponentTransferFunctionElement.prototype, "offset", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGComponentTransferFunctionElement.prototype, "SVGComponentTransferFunctionElement", "offset_get", arguments)}, set:undefined});
