// SVGFEGaussianBlurElement 对象 
SVGFEGaussianBlurElement = function SVGFEGaussianBlurElement(){return framevm.toolsFunc.throwError("TypeError", "Illegal constructor");};
framevm.toolsFunc.safeProto(SVGFEGaussianBlurElement,"SVGFEGaussianBlurElement");
Object.setPrototypeOf(SVGFEGaussianBlurElement.prototype, SVGElement.prototype);
framevm.toolsFunc.defineProperty(SVGFEGaussianBlurElement.prototype, "in1", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGFEGaussianBlurElement.prototype, "SVGFEGaussianBlurElement", "in1_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SVGFEGaussianBlurElement.prototype, "stdDeviationX", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGFEGaussianBlurElement.prototype, "SVGFEGaussianBlurElement", "stdDeviationX_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SVGFEGaussianBlurElement.prototype, "stdDeviationY", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGFEGaussianBlurElement.prototype, "SVGFEGaussianBlurElement", "stdDeviationY_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SVGFEGaussianBlurElement.prototype, "x", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGFEGaussianBlurElement.prototype, "SVGFEGaussianBlurElement", "x_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SVGFEGaussianBlurElement.prototype, "y", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGFEGaussianBlurElement.prototype, "SVGFEGaussianBlurElement", "y_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SVGFEGaussianBlurElement.prototype, "width", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGFEGaussianBlurElement.prototype, "SVGFEGaussianBlurElement", "width_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SVGFEGaussianBlurElement.prototype, "height", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGFEGaussianBlurElement.prototype, "SVGFEGaussianBlurElement", "height_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SVGFEGaussianBlurElement.prototype, "result", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGFEGaussianBlurElement.prototype, "SVGFEGaussianBlurElement", "result_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SVGFEGaussianBlurElement.prototype, "setStdDeviation", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, SVGFEGaussianBlurElement.prototype, "SVGFEGaussianBlurElement", "setStdDeviation", arguments)}});
