// SVGFEDropShadowElement 对象 
SVGFEDropShadowElement = function SVGFEDropShadowElement(){return framevm.toolsFunc.throwError("TypeError", "Illegal constructor");};
framevm.toolsFunc.safeProto(SVGFEDropShadowElement,"SVGFEDropShadowElement");
Object.setPrototypeOf(SVGFEDropShadowElement.prototype, SVGElement.prototype);
framevm.toolsFunc.defineProperty(SVGFEDropShadowElement.prototype, "in1", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGFEDropShadowElement.prototype, "SVGFEDropShadowElement", "in1_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SVGFEDropShadowElement.prototype, "dx", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGFEDropShadowElement.prototype, "SVGFEDropShadowElement", "dx_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SVGFEDropShadowElement.prototype, "dy", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGFEDropShadowElement.prototype, "SVGFEDropShadowElement", "dy_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SVGFEDropShadowElement.prototype, "stdDeviationX", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGFEDropShadowElement.prototype, "SVGFEDropShadowElement", "stdDeviationX_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SVGFEDropShadowElement.prototype, "stdDeviationY", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGFEDropShadowElement.prototype, "SVGFEDropShadowElement", "stdDeviationY_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SVGFEDropShadowElement.prototype, "x", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGFEDropShadowElement.prototype, "SVGFEDropShadowElement", "x_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SVGFEDropShadowElement.prototype, "y", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGFEDropShadowElement.prototype, "SVGFEDropShadowElement", "y_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SVGFEDropShadowElement.prototype, "width", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGFEDropShadowElement.prototype, "SVGFEDropShadowElement", "width_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SVGFEDropShadowElement.prototype, "height", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGFEDropShadowElement.prototype, "SVGFEDropShadowElement", "height_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SVGFEDropShadowElement.prototype, "result", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGFEDropShadowElement.prototype, "SVGFEDropShadowElement", "result_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SVGFEDropShadowElement.prototype, "setStdDeviation", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, SVGFEDropShadowElement.prototype, "SVGFEDropShadowElement", "setStdDeviation", arguments)}});
