// SVGFEConvolveMatrixElement 对象 
SVGFEConvolveMatrixElement = function SVGFEConvolveMatrixElement(){return framevm.toolsFunc.throwError("TypeError", "Illegal constructor");};
framevm.toolsFunc.safeProto(SVGFEConvolveMatrixElement,"SVGFEConvolveMatrixElement");
Object.setPrototypeOf(SVGFEConvolveMatrixElement.prototype, SVGElement.prototype);
framevm.toolsFunc.defineProperty(SVGFEConvolveMatrixElement, "SVG_EDGEMODE_NONE", {configurable:false, enumerable:true, writable:false, value:3});
framevm.toolsFunc.defineProperty(SVGFEConvolveMatrixElement, "SVG_EDGEMODE_WRAP", {configurable:false, enumerable:true, writable:false, value:2});
framevm.toolsFunc.defineProperty(SVGFEConvolveMatrixElement, "SVG_EDGEMODE_DUPLICATE", {configurable:false, enumerable:true, writable:false, value:1});
framevm.toolsFunc.defineProperty(SVGFEConvolveMatrixElement, "SVG_EDGEMODE_UNKNOWN", {configurable:false, enumerable:true, writable:false, value:0});
framevm.toolsFunc.defineProperty(SVGFEConvolveMatrixElement.prototype, "SVG_EDGEMODE_NONE", {configurable:false, enumerable:true, writable:false, value:3});
framevm.toolsFunc.defineProperty(SVGFEConvolveMatrixElement.prototype, "SVG_EDGEMODE_WRAP", {configurable:false, enumerable:true, writable:false, value:2});
framevm.toolsFunc.defineProperty(SVGFEConvolveMatrixElement.prototype, "SVG_EDGEMODE_DUPLICATE", {configurable:false, enumerable:true, writable:false, value:1});
framevm.toolsFunc.defineProperty(SVGFEConvolveMatrixElement.prototype, "SVG_EDGEMODE_UNKNOWN", {configurable:false, enumerable:true, writable:false, value:0});
framevm.toolsFunc.defineProperty(SVGFEConvolveMatrixElement.prototype, "in1", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGFEConvolveMatrixElement.prototype, "SVGFEConvolveMatrixElement", "in1_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SVGFEConvolveMatrixElement.prototype, "orderX", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGFEConvolveMatrixElement.prototype, "SVGFEConvolveMatrixElement", "orderX_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SVGFEConvolveMatrixElement.prototype, "orderY", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGFEConvolveMatrixElement.prototype, "SVGFEConvolveMatrixElement", "orderY_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SVGFEConvolveMatrixElement.prototype, "kernelMatrix", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGFEConvolveMatrixElement.prototype, "SVGFEConvolveMatrixElement", "kernelMatrix_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SVGFEConvolveMatrixElement.prototype, "divisor", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGFEConvolveMatrixElement.prototype, "SVGFEConvolveMatrixElement", "divisor_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SVGFEConvolveMatrixElement.prototype, "bias", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGFEConvolveMatrixElement.prototype, "SVGFEConvolveMatrixElement", "bias_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SVGFEConvolveMatrixElement.prototype, "targetX", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGFEConvolveMatrixElement.prototype, "SVGFEConvolveMatrixElement", "targetX_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SVGFEConvolveMatrixElement.prototype, "targetY", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGFEConvolveMatrixElement.prototype, "SVGFEConvolveMatrixElement", "targetY_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SVGFEConvolveMatrixElement.prototype, "edgeMode", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGFEConvolveMatrixElement.prototype, "SVGFEConvolveMatrixElement", "edgeMode_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SVGFEConvolveMatrixElement.prototype, "kernelUnitLengthX", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGFEConvolveMatrixElement.prototype, "SVGFEConvolveMatrixElement", "kernelUnitLengthX_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SVGFEConvolveMatrixElement.prototype, "kernelUnitLengthY", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGFEConvolveMatrixElement.prototype, "SVGFEConvolveMatrixElement", "kernelUnitLengthY_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SVGFEConvolveMatrixElement.prototype, "preserveAlpha", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGFEConvolveMatrixElement.prototype, "SVGFEConvolveMatrixElement", "preserveAlpha_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SVGFEConvolveMatrixElement.prototype, "x", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGFEConvolveMatrixElement.prototype, "SVGFEConvolveMatrixElement", "x_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SVGFEConvolveMatrixElement.prototype, "y", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGFEConvolveMatrixElement.prototype, "SVGFEConvolveMatrixElement", "y_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SVGFEConvolveMatrixElement.prototype, "width", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGFEConvolveMatrixElement.prototype, "SVGFEConvolveMatrixElement", "width_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SVGFEConvolveMatrixElement.prototype, "height", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGFEConvolveMatrixElement.prototype, "SVGFEConvolveMatrixElement", "height_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SVGFEConvolveMatrixElement.prototype, "result", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGFEConvolveMatrixElement.prototype, "SVGFEConvolveMatrixElement", "result_get", arguments)}, set:undefined});
