// SVGFESpecularLightingElement 对象 
SVGFESpecularLightingElement = function SVGFESpecularLightingElement(){return framevm.toolsFunc.throwError("TypeError", "Illegal constructor");};
framevm.toolsFunc.safeProto(SVGFESpecularLightingElement,"SVGFESpecularLightingElement");
Object.setPrototypeOf(SVGFESpecularLightingElement.prototype, SVGElement.prototype);
framevm.toolsFunc.defineProperty(SVGFESpecularLightingElement.prototype, "in1", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGFESpecularLightingElement.prototype, "SVGFESpecularLightingElement", "in1_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SVGFESpecularLightingElement.prototype, "surfaceScale", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGFESpecularLightingElement.prototype, "SVGFESpecularLightingElement", "surfaceScale_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SVGFESpecularLightingElement.prototype, "specularConstant", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGFESpecularLightingElement.prototype, "SVGFESpecularLightingElement", "specularConstant_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SVGFESpecularLightingElement.prototype, "specularExponent", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGFESpecularLightingElement.prototype, "SVGFESpecularLightingElement", "specularExponent_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SVGFESpecularLightingElement.prototype, "kernelUnitLengthX", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGFESpecularLightingElement.prototype, "SVGFESpecularLightingElement", "kernelUnitLengthX_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SVGFESpecularLightingElement.prototype, "kernelUnitLengthY", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGFESpecularLightingElement.prototype, "SVGFESpecularLightingElement", "kernelUnitLengthY_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SVGFESpecularLightingElement.prototype, "x", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGFESpecularLightingElement.prototype, "SVGFESpecularLightingElement", "x_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SVGFESpecularLightingElement.prototype, "y", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGFESpecularLightingElement.prototype, "SVGFESpecularLightingElement", "y_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SVGFESpecularLightingElement.prototype, "width", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGFESpecularLightingElement.prototype, "SVGFESpecularLightingElement", "width_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SVGFESpecularLightingElement.prototype, "height", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGFESpecularLightingElement.prototype, "SVGFESpecularLightingElement", "height_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SVGFESpecularLightingElement.prototype, "result", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGFESpecularLightingElement.prototype, "SVGFESpecularLightingElement", "result_get", arguments)}, set:undefined});
