// SVGFEDiffuseLightingElement 对象 
SVGFEDiffuseLightingElement = function SVGFEDiffuseLightingElement(){return framevm.toolsFunc.throwError("TypeError", "Illegal constructor");};
framevm.toolsFunc.safeProto(SVGFEDiffuseLightingElement,"SVGFEDiffuseLightingElement");
Object.setPrototypeOf(SVGFEDiffuseLightingElement.prototype, SVGElement.prototype);
framevm.toolsFunc.defineProperty(SVGFEDiffuseLightingElement.prototype, "in1", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGFEDiffuseLightingElement.prototype, "SVGFEDiffuseLightingElement", "in1_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SVGFEDiffuseLightingElement.prototype, "surfaceScale", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGFEDiffuseLightingElement.prototype, "SVGFEDiffuseLightingElement", "surfaceScale_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SVGFEDiffuseLightingElement.prototype, "diffuseConstant", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGFEDiffuseLightingElement.prototype, "SVGFEDiffuseLightingElement", "diffuseConstant_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SVGFEDiffuseLightingElement.prototype, "kernelUnitLengthX", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGFEDiffuseLightingElement.prototype, "SVGFEDiffuseLightingElement", "kernelUnitLengthX_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SVGFEDiffuseLightingElement.prototype, "kernelUnitLengthY", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGFEDiffuseLightingElement.prototype, "SVGFEDiffuseLightingElement", "kernelUnitLengthY_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SVGFEDiffuseLightingElement.prototype, "x", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGFEDiffuseLightingElement.prototype, "SVGFEDiffuseLightingElement", "x_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SVGFEDiffuseLightingElement.prototype, "y", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGFEDiffuseLightingElement.prototype, "SVGFEDiffuseLightingElement", "y_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SVGFEDiffuseLightingElement.prototype, "width", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGFEDiffuseLightingElement.prototype, "SVGFEDiffuseLightingElement", "width_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SVGFEDiffuseLightingElement.prototype, "height", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGFEDiffuseLightingElement.prototype, "SVGFEDiffuseLightingElement", "height_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SVGFEDiffuseLightingElement.prototype, "result", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGFEDiffuseLightingElement.prototype, "SVGFEDiffuseLightingElement", "result_get", arguments)}, set:undefined});
