// SVGMatrix 对象 
SVGMatrix = function SVGMatrix(){return framevm.toolsFunc.throwError("TypeError", "Illegal constructor");};
framevm.toolsFunc.safeProto(SVGMatrix,"SVGMatrix");
framevm.toolsFunc.defineProperty(SVGMatrix.prototype, "a", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGMatrix.prototype, "SVGMatrix", "a_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, SVGMatrix.prototype, "SVGMatrix", "a_set", arguments)}});
framevm.toolsFunc.defineProperty(SVGMatrix.prototype, "b", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGMatrix.prototype, "SVGMatrix", "b_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, SVGMatrix.prototype, "SVGMatrix", "b_set", arguments)}});
framevm.toolsFunc.defineProperty(SVGMatrix.prototype, "c", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGMatrix.prototype, "SVGMatrix", "c_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, SVGMatrix.prototype, "SVGMatrix", "c_set", arguments)}});
framevm.toolsFunc.defineProperty(SVGMatrix.prototype, "d", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGMatrix.prototype, "SVGMatrix", "d_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, SVGMatrix.prototype, "SVGMatrix", "d_set", arguments)}});
framevm.toolsFunc.defineProperty(SVGMatrix.prototype, "e", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGMatrix.prototype, "SVGMatrix", "e_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, SVGMatrix.prototype, "SVGMatrix", "e_set", arguments)}});
framevm.toolsFunc.defineProperty(SVGMatrix.prototype, "f", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGMatrix.prototype, "SVGMatrix", "f_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, SVGMatrix.prototype, "SVGMatrix", "f_set", arguments)}});
framevm.toolsFunc.defineProperty(SVGMatrix.prototype, "flipX", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, SVGMatrix.prototype, "SVGMatrix", "flipX", arguments)}});
framevm.toolsFunc.defineProperty(SVGMatrix.prototype, "flipY", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, SVGMatrix.prototype, "SVGMatrix", "flipY", arguments)}});
framevm.toolsFunc.defineProperty(SVGMatrix.prototype, "inverse", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, SVGMatrix.prototype, "SVGMatrix", "inverse", arguments)}});
framevm.toolsFunc.defineProperty(SVGMatrix.prototype, "multiply", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, SVGMatrix.prototype, "SVGMatrix", "multiply", arguments)}});
framevm.toolsFunc.defineProperty(SVGMatrix.prototype, "rotate", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, SVGMatrix.prototype, "SVGMatrix", "rotate", arguments)}});
framevm.toolsFunc.defineProperty(SVGMatrix.prototype, "rotateFromVector", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, SVGMatrix.prototype, "SVGMatrix", "rotateFromVector", arguments)}});
framevm.toolsFunc.defineProperty(SVGMatrix.prototype, "scale", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, SVGMatrix.prototype, "SVGMatrix", "scale", arguments)}});
framevm.toolsFunc.defineProperty(SVGMatrix.prototype, "scaleNonUniform", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, SVGMatrix.prototype, "SVGMatrix", "scaleNonUniform", arguments)}});
framevm.toolsFunc.defineProperty(SVGMatrix.prototype, "skewX", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, SVGMatrix.prototype, "SVGMatrix", "skewX", arguments)}});
framevm.toolsFunc.defineProperty(SVGMatrix.prototype, "skewY", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, SVGMatrix.prototype, "SVGMatrix", "skewY", arguments)}});
framevm.toolsFunc.defineProperty(SVGMatrix.prototype, "translate", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, SVGMatrix.prototype, "SVGMatrix", "translate", arguments)}});
