// SVGPatternElement 对象 
SVGPatternElement = function SVGPatternElement(){return framevm.toolsFunc.throwError("TypeError", "Illegal constructor");};
framevm.toolsFunc.safeProto(SVGPatternElement,"SVGPatternElement");
Object.setPrototypeOf(SVGPatternElement.prototype, SVGElement.prototype);
framevm.toolsFunc.defineProperty(SVGPatternElement.prototype, "patternUnits", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGPatternElement.prototype, "SVGPatternElement", "patternUnits_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SVGPatternElement.prototype, "patternContentUnits", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGPatternElement.prototype, "SVGPatternElement", "patternContentUnits_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SVGPatternElement.prototype, "patternTransform", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGPatternElement.prototype, "SVGPatternElement", "patternTransform_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SVGPatternElement.prototype, "x", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGPatternElement.prototype, "SVGPatternElement", "x_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SVGPatternElement.prototype, "y", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGPatternElement.prototype, "SVGPatternElement", "y_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SVGPatternElement.prototype, "width", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGPatternElement.prototype, "SVGPatternElement", "width_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SVGPatternElement.prototype, "height", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGPatternElement.prototype, "SVGPatternElement", "height_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SVGPatternElement.prototype, "viewBox", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGPatternElement.prototype, "SVGPatternElement", "viewBox_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SVGPatternElement.prototype, "preserveAspectRatio", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGPatternElement.prototype, "SVGPatternElement", "preserveAspectRatio_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SVGPatternElement.prototype, "href", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGPatternElement.prototype, "SVGPatternElement", "href_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SVGPatternElement.prototype, "requiredExtensions", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGPatternElement.prototype, "SVGPatternElement", "requiredExtensions_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SVGPatternElement.prototype, "systemLanguage", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGPatternElement.prototype, "SVGPatternElement", "systemLanguage_get", arguments)}, set:undefined});
