// SVGStyleElement 对象 
SVGStyleElement = function SVGStyleElement(){return framevm.toolsFunc.throwError("TypeError", "Illegal constructor");};
framevm.toolsFunc.safeProto(SVGStyleElement,"SVGStyleElement");
Object.setPrototypeOf(SVGStyleElement.prototype, SVGElement.prototype);
framevm.toolsFunc.defineProperty(SVGStyleElement.prototype, "type", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGStyleElement.prototype, "SVGStyleElement", "type_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, SVGStyleElement.prototype, "SVGStyleElement", "type_set", arguments)}});
framevm.toolsFunc.defineProperty(SVGStyleElement.prototype, "media", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGStyleElement.prototype, "SVGStyleElement", "media_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, SVGStyleElement.prototype, "SVGStyleElement", "media_set", arguments)}});
framevm.toolsFunc.defineProperty(SVGStyleElement.prototype, "title", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGStyleElement.prototype, "SVGStyleElement", "title_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, SVGStyleElement.prototype, "SVGStyleElement", "title_set", arguments)}});
framevm.toolsFunc.defineProperty(SVGStyleElement.prototype, "sheet", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGStyleElement.prototype, "SVGStyleElement", "sheet_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SVGStyleElement.prototype, "disabled", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGStyleElement.prototype, "SVGStyleElement", "disabled_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, SVGStyleElement.prototype, "SVGStyleElement", "disabled_set", arguments)}});
