// SVGTextContentElement 对象 
SVGTextContentElement = function SVGTextContentElement(){return framevm.toolsFunc.throwError("TypeError", "Illegal constructor");};
framevm.toolsFunc.safeProto(SVGTextContentElement,"SVGTextContentElement");
Object.setPrototypeOf(SVGTextContentElement.prototype, SVGGraphicsElement.prototype);
framevm.toolsFunc.defineProperty(SVGTextContentElement, "LENGTHADJUST_SPACINGANDGLYPHS", {configurable:false, enumerable:true, writable:false, value:2});
framevm.toolsFunc.defineProperty(SVGTextContentElement, "LENGTHADJUST_SPACING", {configurable:false, enumerable:true, writable:false, value:1});
framevm.toolsFunc.defineProperty(SVGTextContentElement, "LENGTHADJUST_UNKNOWN", {configurable:false, enumerable:true, writable:false, value:0});
framevm.toolsFunc.defineProperty(SVGTextContentElement.prototype, "LENGTHADJUST_SPACINGANDGLYPHS", {configurable:false, enumerable:true, writable:false, value:2});
framevm.toolsFunc.defineProperty(SVGTextContentElement.prototype, "LENGTHADJUST_SPACING", {configurable:false, enumerable:true, writable:false, value:1});
framevm.toolsFunc.defineProperty(SVGTextContentElement.prototype, "LENGTHADJUST_UNKNOWN", {configurable:false, enumerable:true, writable:false, value:0});
framevm.toolsFunc.defineProperty(SVGTextContentElement.prototype, "textLength", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGTextContentElement.prototype, "SVGTextContentElement", "textLength_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SVGTextContentElement.prototype, "lengthAdjust", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGTextContentElement.prototype, "SVGTextContentElement", "lengthAdjust_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SVGTextContentElement.prototype, "getCharNumAtPosition", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, SVGTextContentElement.prototype, "SVGTextContentElement", "getCharNumAtPosition", arguments)}});
framevm.toolsFunc.defineProperty(SVGTextContentElement.prototype, "getComputedTextLength", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, SVGTextContentElement.prototype, "SVGTextContentElement", "getComputedTextLength", arguments)}});
framevm.toolsFunc.defineProperty(SVGTextContentElement.prototype, "getEndPositionOfChar", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, SVGTextContentElement.prototype, "SVGTextContentElement", "getEndPositionOfChar", arguments)}});
framevm.toolsFunc.defineProperty(SVGTextContentElement.prototype, "getExtentOfChar", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, SVGTextContentElement.prototype, "SVGTextContentElement", "getExtentOfChar", arguments)}});
framevm.toolsFunc.defineProperty(SVGTextContentElement.prototype, "getNumberOfChars", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, SVGTextContentElement.prototype, "SVGTextContentElement", "getNumberOfChars", arguments)}});
framevm.toolsFunc.defineProperty(SVGTextContentElement.prototype, "getRotationOfChar", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, SVGTextContentElement.prototype, "SVGTextContentElement", "getRotationOfChar", arguments)}});
framevm.toolsFunc.defineProperty(SVGTextContentElement.prototype, "getStartPositionOfChar", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, SVGTextContentElement.prototype, "SVGTextContentElement", "getStartPositionOfChar", arguments)}});
framevm.toolsFunc.defineProperty(SVGTextContentElement.prototype, "getSubStringLength", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, SVGTextContentElement.prototype, "SVGTextContentElement", "getSubStringLength", arguments)}});
framevm.toolsFunc.defineProperty(SVGTextContentElement.prototype, "selectSubString", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, SVGTextContentElement.prototype, "SVGTextContentElement", "selectSubString", arguments)}});
