// SVGTransformList 对象 
SVGTransformList = function SVGTransformList(){return framevm.toolsFunc.throwError("TypeError", "Illegal constructor");};
framevm.toolsFunc.safeProto(SVGTransformList,"SVGTransformList");
framevm.toolsFunc.defineProperty(SVGTransformList.prototype, "length", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGTransformList.prototype, "SVGTransformList", "length_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SVGTransformList.prototype, "numberOfItems", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SVGTransformList.prototype, "SVGTransformList", "numberOfItems_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(SVGTransformList.prototype, "appendItem", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, SVGTransformList.prototype, "SVGTransformList", "appendItem", arguments)}});
framevm.toolsFunc.defineProperty(SVGTransformList.prototype, "clear", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, SVGTransformList.prototype, "SVGTransformList", "clear", arguments)}});
framevm.toolsFunc.defineProperty(SVGTransformList.prototype, "consolidate", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, SVGTransformList.prototype, "SVGTransformList", "consolidate", arguments)}});
framevm.toolsFunc.defineProperty(SVGTransformList.prototype, "createSVGTransformFromMatrix", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, SVGTransformList.prototype, "SVGTransformList", "createSVGTransformFromMatrix", arguments)}});
framevm.toolsFunc.defineProperty(SVGTransformList.prototype, "getItem", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, SVGTransformList.prototype, "SVGTransformList", "getItem", arguments)}});
framevm.toolsFunc.defineProperty(SVGTransformList.prototype, "initialize", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, SVGTransformList.prototype, "SVGTransformList", "initialize", arguments)}});
framevm.toolsFunc.defineProperty(SVGTransformList.prototype, "insertItemBefore", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, SVGTransformList.prototype, "SVGTransformList", "insertItemBefore", arguments)}});
framevm.toolsFunc.defineProperty(SVGTransformList.prototype, "removeItem", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, SVGTransformList.prototype, "SVGTransformList", "removeItem", arguments)}});
framevm.toolsFunc.defineProperty(SVGTransformList.prototype, "replaceItem", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, SVGTransformList.prototype, "SVGTransformList", "replaceItem", arguments)}});
