// TextTrackCue 对象 
TextTrackCue = function TextTrackCue(){return framevm.toolsFunc.throwError("TypeError", "Illegal constructor");};
framevm.toolsFunc.safeProto(TextTrackCue,"TextTrackCue");
Object.setPrototypeOf(TextTrackCue.prototype, EventTarget.prototype);
framevm.toolsFunc.defineProperty(TextTrackCue.prototype, "track", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, TextTrackCue.prototype, "TextTrackCue", "track_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(TextTrackCue.prototype, "id", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, TextTrackCue.prototype, "TextTrackCue", "id_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, TextTrackCue.prototype, "TextTrackCue", "id_set", arguments)}});
framevm.toolsFunc.defineProperty(TextTrackCue.prototype, "startTime", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, TextTrackCue.prototype, "TextTrackCue", "startTime_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, TextTrackCue.prototype, "TextTrackCue", "startTime_set", arguments)}});
framevm.toolsFunc.defineProperty(TextTrackCue.prototype, "endTime", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, TextTrackCue.prototype, "TextTrackCue", "endTime_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, TextTrackCue.prototype, "TextTrackCue", "endTime_set", arguments)}});
framevm.toolsFunc.defineProperty(TextTrackCue.prototype, "pauseOnExit", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, TextTrackCue.prototype, "TextTrackCue", "pauseOnExit_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, TextTrackCue.prototype, "TextTrackCue", "pauseOnExit_set", arguments)}});
framevm.toolsFunc.defineProperty(TextTrackCue.prototype, "onenter", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, TextTrackCue.prototype, "TextTrackCue", "onenter_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, TextTrackCue.prototype, "TextTrackCue", "onenter_set", arguments)}});
framevm.toolsFunc.defineProperty(TextTrackCue.prototype, "onexit", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, TextTrackCue.prototype, "TextTrackCue", "onexit_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, TextTrackCue.prototype, "TextTrackCue", "onexit_set", arguments)}});
