// TrustedTypePolicyFactory 对象 
TrustedTypePolicyFactory = function TrustedTypePolicyFactory(){return framevm.toolsFunc.throwError("TypeError", "Illegal constructor");};
framevm.toolsFunc.safeProto(TrustedTypePolicyFactory,"TrustedTypePolicyFactory");
Object.setPrototypeOf(TrustedTypePolicyFactory.prototype, EventTarget.prototype);
framevm.toolsFunc.defineProperty(TrustedTypePolicyFactory.prototype, "emptyHTML", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, TrustedTypePolicyFactory.prototype, "TrustedTypePolicyFactory", "emptyHTML_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(TrustedTypePolicyFactory.prototype, "emptyScript", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, TrustedTypePolicyFactory.prototype, "TrustedTypePolicyFactory", "emptyScript_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(TrustedTypePolicyFactory.prototype, "defaultPolicy", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, TrustedTypePolicyFactory.prototype, "TrustedTypePolicyFactory", "defaultPolicy_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(TrustedTypePolicyFactory.prototype, "createPolicy", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, TrustedTypePolicyFactory.prototype, "TrustedTypePolicyFactory", "createPolicy", arguments)}});
framevm.toolsFunc.defineProperty(TrustedTypePolicyFactory.prototype, "getAttributeType", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, TrustedTypePolicyFactory.prototype, "TrustedTypePolicyFactory", "getAttributeType", arguments)}});
framevm.toolsFunc.defineProperty(TrustedTypePolicyFactory.prototype, "getPropertyType", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, TrustedTypePolicyFactory.prototype, "TrustedTypePolicyFactory", "getPropertyType", arguments)}});
framevm.toolsFunc.defineProperty(TrustedTypePolicyFactory.prototype, "getTypeMapping", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, TrustedTypePolicyFactory.prototype, "TrustedTypePolicyFactory", "getTypeMapping", arguments)}});
framevm.toolsFunc.defineProperty(TrustedTypePolicyFactory.prototype, "isHTML", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, TrustedTypePolicyFactory.prototype, "TrustedTypePolicyFactory", "isHTML", arguments)}});
framevm.toolsFunc.defineProperty(TrustedTypePolicyFactory.prototype, "isScript", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, TrustedTypePolicyFactory.prototype, "TrustedTypePolicyFactory", "isScript", arguments)}});
framevm.toolsFunc.defineProperty(TrustedTypePolicyFactory.prototype, "isScriptURL", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, TrustedTypePolicyFactory.prototype, "TrustedTypePolicyFactory", "isScriptURL", arguments)}});
