// ValidityState 对象 
ValidityState = function ValidityState(){return framevm.toolsFunc.throwError("TypeError", "Illegal constructor");};
framevm.toolsFunc.safeProto(ValidityState,"ValidityState");
framevm.toolsFunc.defineProperty(ValidityState.prototype, "valueMissing", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ValidityState.prototype, "ValidityState", "valueMissing_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(ValidityState.prototype, "typeMismatch", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ValidityState.prototype, "ValidityState", "typeMismatch_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(ValidityState.prototype, "patternMismatch", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ValidityState.prototype, "ValidityState", "patternMismatch_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(ValidityState.prototype, "tooLong", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ValidityState.prototype, "ValidityState", "tooLong_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(ValidityState.prototype, "tooShort", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ValidityState.prototype, "ValidityState", "tooShort_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(ValidityState.prototype, "rangeUnderflow", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ValidityState.prototype, "ValidityState", "rangeUnderflow_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(ValidityState.prototype, "rangeOverflow", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ValidityState.prototype, "ValidityState", "rangeOverflow_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(ValidityState.prototype, "stepMismatch", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ValidityState.prototype, "ValidityState", "stepMismatch_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(ValidityState.prototype, "badInput", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ValidityState.prototype, "ValidityState", "badInput_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(ValidityState.prototype, "customError", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ValidityState.prototype, "ValidityState", "customError_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(ValidityState.prototype, "valid", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, ValidityState.prototype, "ValidityState", "valid_get", arguments)}, set:undefined});
