// VideoFrame 对象 
VideoFrame = function VideoFrame(){return framevm.toolsFunc.throwError("TypeError", "Failed to construct 'VideoFrame': 1 argument required, but only 0 present.");};
framevm.toolsFunc.safeProto(VideoFrame,"VideoFrame");
framevm.toolsFunc.defineProperty(VideoFrame.prototype, "format", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, VideoFrame.prototype, "VideoFrame", "format_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(VideoFrame.prototype, "timestamp", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, VideoFrame.prototype, "VideoFrame", "timestamp_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(VideoFrame.prototype, "duration", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, VideoFrame.prototype, "VideoFrame", "duration_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(VideoFrame.prototype, "codedWidth", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, VideoFrame.prototype, "VideoFrame", "codedWidth_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(VideoFrame.prototype, "codedHeight", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, VideoFrame.prototype, "VideoFrame", "codedHeight_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(VideoFrame.prototype, "codedRect", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, VideoFrame.prototype, "VideoFrame", "codedRect_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(VideoFrame.prototype, "visibleRect", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, VideoFrame.prototype, "VideoFrame", "visibleRect_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(VideoFrame.prototype, "displayWidth", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, VideoFrame.prototype, "VideoFrame", "displayWidth_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(VideoFrame.prototype, "displayHeight", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, VideoFrame.prototype, "VideoFrame", "displayHeight_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(VideoFrame.prototype, "colorSpace", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, VideoFrame.prototype, "VideoFrame", "colorSpace_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(VideoFrame.prototype, "allocationSize", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, VideoFrame.prototype, "VideoFrame", "allocationSize", arguments)}});
framevm.toolsFunc.defineProperty(VideoFrame.prototype, "clone", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, VideoFrame.prototype, "VideoFrame", "clone", arguments)}});
framevm.toolsFunc.defineProperty(VideoFrame.prototype, "close", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, VideoFrame.prototype, "VideoFrame", "close", arguments)}});
framevm.toolsFunc.defineProperty(VideoFrame.prototype, "copyTo", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, VideoFrame.prototype, "VideoFrame", "copyTo", arguments)}});
