// VTTCue 对象 
VTTCue = function VTTCue(){return framevm.toolsFunc.throwError("TypeError", "Failed to construct 'VTTCue': 3 arguments required, but only 0 present.");};
framevm.toolsFunc.safeProto(VTTCue,"VTTCue");
Object.setPrototypeOf(VTTCue.prototype, TextTrackCue.prototype);
framevm.toolsFunc.defineProperty(VTTCue.prototype, "vertical", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, VTTCue.prototype, "VTTCue", "vertical_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, VTTCue.prototype, "VTTCue", "vertical_set", arguments)}});
framevm.toolsFunc.defineProperty(VTTCue.prototype, "snapToLines", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, VTTCue.prototype, "VTTCue", "snapToLines_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, VTTCue.prototype, "VTTCue", "snapToLines_set", arguments)}});
framevm.toolsFunc.defineProperty(VTTCue.prototype, "line", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, VTTCue.prototype, "VTTCue", "line_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, VTTCue.prototype, "VTTCue", "line_set", arguments)}});
framevm.toolsFunc.defineProperty(VTTCue.prototype, "position", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, VTTCue.prototype, "VTTCue", "position_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, VTTCue.prototype, "VTTCue", "position_set", arguments)}});
framevm.toolsFunc.defineProperty(VTTCue.prototype, "size", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, VTTCue.prototype, "VTTCue", "size_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, VTTCue.prototype, "VTTCue", "size_set", arguments)}});
framevm.toolsFunc.defineProperty(VTTCue.prototype, "align", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, VTTCue.prototype, "VTTCue", "align_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, VTTCue.prototype, "VTTCue", "align_set", arguments)}});
framevm.toolsFunc.defineProperty(VTTCue.prototype, "text", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, VTTCue.prototype, "VTTCue", "text_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, VTTCue.prototype, "VTTCue", "text_set", arguments)}});
framevm.toolsFunc.defineProperty(VTTCue.prototype, "getCueAsHTML", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, VTTCue.prototype, "VTTCue", "getCueAsHTML", arguments)}});
