// SpeechRecognition 对象 
SpeechRecognition = function SpeechRecognition(){};
framevm.toolsFunc.safeProto(SpeechRecognition,"SpeechRecognition");
Object.setPrototypeOf(SpeechRecognition.prototype, EventTarget.prototype);
framevm.toolsFunc.defineProperty(SpeechRecognition.prototype, "grammars", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SpeechRecognition.prototype, "SpeechRecognition", "grammars_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, SpeechRecognition.prototype, "SpeechRecognition", "grammars_set", arguments)}});
framevm.toolsFunc.defineProperty(SpeechRecognition.prototype, "lang", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SpeechRecognition.prototype, "SpeechRecognition", "lang_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, SpeechRecognition.prototype, "SpeechRecognition", "lang_set", arguments)}});
framevm.toolsFunc.defineProperty(SpeechRecognition.prototype, "continuous", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SpeechRecognition.prototype, "SpeechRecognition", "continuous_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, SpeechRecognition.prototype, "SpeechRecognition", "continuous_set", arguments)}});
framevm.toolsFunc.defineProperty(SpeechRecognition.prototype, "interimResults", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SpeechRecognition.prototype, "SpeechRecognition", "interimResults_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, SpeechRecognition.prototype, "SpeechRecognition", "interimResults_set", arguments)}});
framevm.toolsFunc.defineProperty(SpeechRecognition.prototype, "maxAlternatives", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SpeechRecognition.prototype, "SpeechRecognition", "maxAlternatives_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, SpeechRecognition.prototype, "SpeechRecognition", "maxAlternatives_set", arguments)}});
framevm.toolsFunc.defineProperty(SpeechRecognition.prototype, "onaudiostart", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SpeechRecognition.prototype, "SpeechRecognition", "onaudiostart_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, SpeechRecognition.prototype, "SpeechRecognition", "onaudiostart_set", arguments)}});
framevm.toolsFunc.defineProperty(SpeechRecognition.prototype, "onsoundstart", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SpeechRecognition.prototype, "SpeechRecognition", "onsoundstart_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, SpeechRecognition.prototype, "SpeechRecognition", "onsoundstart_set", arguments)}});
framevm.toolsFunc.defineProperty(SpeechRecognition.prototype, "onspeechstart", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SpeechRecognition.prototype, "SpeechRecognition", "onspeechstart_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, SpeechRecognition.prototype, "SpeechRecognition", "onspeechstart_set", arguments)}});
framevm.toolsFunc.defineProperty(SpeechRecognition.prototype, "onspeechend", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SpeechRecognition.prototype, "SpeechRecognition", "onspeechend_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, SpeechRecognition.prototype, "SpeechRecognition", "onspeechend_set", arguments)}});
framevm.toolsFunc.defineProperty(SpeechRecognition.prototype, "onsoundend", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SpeechRecognition.prototype, "SpeechRecognition", "onsoundend_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, SpeechRecognition.prototype, "SpeechRecognition", "onsoundend_set", arguments)}});
framevm.toolsFunc.defineProperty(SpeechRecognition.prototype, "onaudioend", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SpeechRecognition.prototype, "SpeechRecognition", "onaudioend_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, SpeechRecognition.prototype, "SpeechRecognition", "onaudioend_set", arguments)}});
framevm.toolsFunc.defineProperty(SpeechRecognition.prototype, "onresult", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SpeechRecognition.prototype, "SpeechRecognition", "onresult_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, SpeechRecognition.prototype, "SpeechRecognition", "onresult_set", arguments)}});
framevm.toolsFunc.defineProperty(SpeechRecognition.prototype, "onnomatch", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SpeechRecognition.prototype, "SpeechRecognition", "onnomatch_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, SpeechRecognition.prototype, "SpeechRecognition", "onnomatch_set", arguments)}});
framevm.toolsFunc.defineProperty(SpeechRecognition.prototype, "onerror", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SpeechRecognition.prototype, "SpeechRecognition", "onerror_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, SpeechRecognition.prototype, "SpeechRecognition", "onerror_set", arguments)}});
framevm.toolsFunc.defineProperty(SpeechRecognition.prototype, "onstart", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SpeechRecognition.prototype, "SpeechRecognition", "onstart_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, SpeechRecognition.prototype, "SpeechRecognition", "onstart_set", arguments)}});
framevm.toolsFunc.defineProperty(SpeechRecognition.prototype, "onend", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, SpeechRecognition.prototype, "SpeechRecognition", "onend_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, SpeechRecognition.prototype, "SpeechRecognition", "onend_set", arguments)}});
framevm.toolsFunc.defineProperty(SpeechRecognition.prototype, "abort", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, SpeechRecognition.prototype, "SpeechRecognition", "abort", arguments)}});
framevm.toolsFunc.defineProperty(SpeechRecognition.prototype, "start", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, SpeechRecognition.prototype, "SpeechRecognition", "start", arguments)}});
framevm.toolsFunc.defineProperty(SpeechRecognition.prototype, "stop", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, SpeechRecognition.prototype, "SpeechRecognition", "stop", arguments)}});
