// WebTransportDatagramDuplexStream 对象 
WebTransportDatagramDuplexStream = function WebTransportDatagramDuplexStream(){return framevm.toolsFunc.throwError("TypeError", "Illegal constructor");};
framevm.toolsFunc.safeProto(WebTransportDatagramDuplexStream,"WebTransportDatagramDuplexStream");
framevm.toolsFunc.defineProperty(WebTransportDatagramDuplexStream.prototype, "readable", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, WebTransportDatagramDuplexStream.prototype, "WebTransportDatagramDuplexStream", "readable_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(WebTransportDatagramDuplexStream.prototype, "writable", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, WebTransportDatagramDuplexStream.prototype, "WebTransportDatagramDuplexStream", "writable_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(WebTransportDatagramDuplexStream.prototype, "maxDatagramSize", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, WebTransportDatagramDuplexStream.prototype, "WebTransportDatagramDuplexStream", "maxDatagramSize_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(WebTransportDatagramDuplexStream.prototype, "incomingMaxAge", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, WebTransportDatagramDuplexStream.prototype, "WebTransportDatagramDuplexStream", "incomingMaxAge_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, WebTransportDatagramDuplexStream.prototype, "WebTransportDatagramDuplexStream", "incomingMaxAge_set", arguments)}});
framevm.toolsFunc.defineProperty(WebTransportDatagramDuplexStream.prototype, "outgoingMaxAge", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, WebTransportDatagramDuplexStream.prototype, "WebTransportDatagramDuplexStream", "outgoingMaxAge_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, WebTransportDatagramDuplexStream.prototype, "WebTransportDatagramDuplexStream", "outgoingMaxAge_set", arguments)}});
framevm.toolsFunc.defineProperty(WebTransportDatagramDuplexStream.prototype, "incomingHighWaterMark", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, WebTransportDatagramDuplexStream.prototype, "WebTransportDatagramDuplexStream", "incomingHighWaterMark_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, WebTransportDatagramDuplexStream.prototype, "WebTransportDatagramDuplexStream", "incomingHighWaterMark_set", arguments)}});
framevm.toolsFunc.defineProperty(WebTransportDatagramDuplexStream.prototype, "outgoingHighWaterMark", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, WebTransportDatagramDuplexStream.prototype, "WebTransportDatagramDuplexStream", "outgoingHighWaterMark_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, WebTransportDatagramDuplexStream.prototype, "WebTransportDatagramDuplexStream", "outgoingHighWaterMark_set", arguments)}});
