// WebTransport 对象 
WebTransport = function WebTransport(){return framevm.toolsFunc.throwError("TypeError", "Failed to construct 'WebTransport': 1 argument required, but only 0 present.");};
framevm.toolsFunc.safeProto(WebTransport,"WebTransport");
framevm.toolsFunc.defineProperty(WebTransport.prototype, "incomingUnidirectionalStreams", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, WebTransport.prototype, "WebTransport", "incomingUnidirectionalStreams_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(WebTransport.prototype, "incomingBidirectionalStreams", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, WebTransport.prototype, "WebTransport", "incomingBidirectionalStreams_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(WebTransport.prototype, "datagrams", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, WebTransport.prototype, "WebTransport", "datagrams_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(WebTransport.prototype, "ready", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, WebTransport.prototype, "WebTransport", "ready_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(WebTransport.prototype, "closed", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, WebTransport.prototype, "WebTransport", "closed_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(WebTransport.prototype, "close", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, WebTransport.prototype, "WebTransport", "close", arguments)}});
framevm.toolsFunc.defineProperty(WebTransport.prototype, "createBidirectionalStream", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, WebTransport.prototype, "WebTransport", "createBidirectionalStream", arguments)}});
framevm.toolsFunc.defineProperty(WebTransport.prototype, "createUnidirectionalStream", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, WebTransport.prototype, "WebTransport", "createUnidirectionalStream", arguments)}});
