// WritableStreamDefaultWriter 对象 
WritableStreamDefaultWriter = function WritableStreamDefaultWriter(){return framevm.toolsFunc.throwError("TypeError", "Failed to construct 'WritableStreamDefaultWriter': 1 argument required, but only 0 present.");};
framevm.toolsFunc.safeProto(WritableStreamDefaultWriter,"WritableStreamDefaultWriter");
framevm.toolsFunc.defineProperty(WritableStreamDefaultWriter.prototype, "closed", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, WritableStreamDefaultWriter.prototype, "WritableStreamDefaultWriter", "closed_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(WritableStreamDefaultWriter.prototype, "desiredSize", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, WritableStreamDefaultWriter.prototype, "WritableStreamDefaultWriter", "desiredSize_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(WritableStreamDefaultWriter.prototype, "ready", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, WritableStreamDefaultWriter.prototype, "WritableStreamDefaultWriter", "ready_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(WritableStreamDefaultWriter.prototype, "abort", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, WritableStreamDefaultWriter.prototype, "WritableStreamDefaultWriter", "abort", arguments)}});
framevm.toolsFunc.defineProperty(WritableStreamDefaultWriter.prototype, "close", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, WritableStreamDefaultWriter.prototype, "WritableStreamDefaultWriter", "close", arguments)}});
framevm.toolsFunc.defineProperty(WritableStreamDefaultWriter.prototype, "releaseLock", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, WritableStreamDefaultWriter.prototype, "WritableStreamDefaultWriter", "releaseLock", arguments)}});
framevm.toolsFunc.defineProperty(WritableStreamDefaultWriter.prototype, "write", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, WritableStreamDefaultWriter.prototype, "WritableStreamDefaultWriter", "write", arguments)}});
