// XRSession 对象 
XRSession = function XRSession(){return framevm.toolsFunc.throwError("TypeError", "Illegal constructor");};
framevm.toolsFunc.safeProto(XRSession,"XRSession");
Object.setPrototypeOf(XRSession.prototype, EventTarget.prototype);
framevm.toolsFunc.defineProperty(XRSession.prototype, "environmentBlendMode", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, XRSession.prototype, "XRSession", "environmentBlendMode_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(XRSession.prototype, "interactionMode", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, XRSession.prototype, "XRSession", "interactionMode_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(XRSession.prototype, "visibilityState", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, XRSession.prototype, "XRSession", "visibilityState_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(XRSession.prototype, "renderState", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, XRSession.prototype, "XRSession", "renderState_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(XRSession.prototype, "inputSources", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, XRSession.prototype, "XRSession", "inputSources_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(XRSession.prototype, "domOverlayState", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, XRSession.prototype, "XRSession", "domOverlayState_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(XRSession.prototype, "preferredReflectionFormat", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, XRSession.prototype, "XRSession", "preferredReflectionFormat_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(XRSession.prototype, "enabledFeatures", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, XRSession.prototype, "XRSession", "enabledFeatures_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(XRSession.prototype, "onend", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, XRSession.prototype, "XRSession", "onend_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, XRSession.prototype, "XRSession", "onend_set", arguments)}});
framevm.toolsFunc.defineProperty(XRSession.prototype, "onselect", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, XRSession.prototype, "XRSession", "onselect_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, XRSession.prototype, "XRSession", "onselect_set", arguments)}});
framevm.toolsFunc.defineProperty(XRSession.prototype, "oninputsourceschange", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, XRSession.prototype, "XRSession", "oninputsourceschange_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, XRSession.prototype, "XRSession", "oninputsourceschange_set", arguments)}});
framevm.toolsFunc.defineProperty(XRSession.prototype, "onselectstart", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, XRSession.prototype, "XRSession", "onselectstart_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, XRSession.prototype, "XRSession", "onselectstart_set", arguments)}});
framevm.toolsFunc.defineProperty(XRSession.prototype, "onselectend", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, XRSession.prototype, "XRSession", "onselectend_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, XRSession.prototype, "XRSession", "onselectend_set", arguments)}});
framevm.toolsFunc.defineProperty(XRSession.prototype, "onvisibilitychange", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, XRSession.prototype, "XRSession", "onvisibilitychange_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, XRSession.prototype, "XRSession", "onvisibilitychange_set", arguments)}});
framevm.toolsFunc.defineProperty(XRSession.prototype, "onsqueeze", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, XRSession.prototype, "XRSession", "onsqueeze_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, XRSession.prototype, "XRSession", "onsqueeze_set", arguments)}});
framevm.toolsFunc.defineProperty(XRSession.prototype, "onsqueezestart", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, XRSession.prototype, "XRSession", "onsqueezestart_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, XRSession.prototype, "XRSession", "onsqueezestart_set", arguments)}});
framevm.toolsFunc.defineProperty(XRSession.prototype, "onsqueezeend", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, XRSession.prototype, "XRSession", "onsqueezeend_get", arguments)}, set:function (){return framevm.toolsFunc.dispatch(this, XRSession.prototype, "XRSession", "onsqueezeend_set", arguments)}});
framevm.toolsFunc.defineProperty(XRSession.prototype, "depthUsage", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, XRSession.prototype, "XRSession", "depthUsage_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(XRSession.prototype, "depthDataFormat", {configurable:true, enumerable:true, get:function (){return framevm.toolsFunc.dispatch(this, XRSession.prototype, "XRSession", "depthDataFormat_get", arguments)}, set:undefined});
framevm.toolsFunc.defineProperty(XRSession.prototype, "cancelAnimationFrame", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, XRSession.prototype, "XRSession", "cancelAnimationFrame", arguments)}});
framevm.toolsFunc.defineProperty(XRSession.prototype, "end", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, XRSession.prototype, "XRSession", "end", arguments)}});
framevm.toolsFunc.defineProperty(XRSession.prototype, "requestAnimationFrame", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, XRSession.prototype, "XRSession", "requestAnimationFrame", arguments)}});
framevm.toolsFunc.defineProperty(XRSession.prototype, "requestHitTestSource", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, XRSession.prototype, "XRSession", "requestHitTestSource", arguments)}});
framevm.toolsFunc.defineProperty(XRSession.prototype, "requestHitTestSourceForTransientInput", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, XRSession.prototype, "XRSession", "requestHitTestSourceForTransientInput", arguments)}});
framevm.toolsFunc.defineProperty(XRSession.prototype, "requestLightProbe", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, XRSession.prototype, "XRSession", "requestLightProbe", arguments)}});
framevm.toolsFunc.defineProperty(XRSession.prototype, "requestReferenceSpace", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, XRSession.prototype, "XRSession", "requestReferenceSpace", arguments)}});
framevm.toolsFunc.defineProperty(XRSession.prototype, "updateRenderState", {configurable:true, enumerable:true, writable:true, value:function (){return framevm.toolsFunc.dispatch(this, XRSession.prototype, "XRSession", "updateRenderState", arguments)}});
